### ISSUE TITLE
[Unity] Responses are handled in main thread

### ISSUE THREAD

**Issue by hallucinogen** [parse-community/Parse-SDK-dotNET#101]
Copied from external bug report:

Asynchronous API calls like FindAsync can and do block the main thread when the response is received by the client. Operations like parsing the response data are supposed to happen in background threads, as described in the Tasks API, but they seem to be happening on the main thread anyway.

To isolate this, I created a bare bones project in Unity that calls FindAsync with no continuation. If the data requested takes a long time to parse (I've seen 3.5 seconds for a large string with a lot of escape characters), this blocks the main thread, preventing rendering and user input until the parsing is completed.

In the profiler it appears that tasks are calling their continuations directly instead of spawning separate tasks. This may be an optimization to prevent excess thread creation, but there need to be safeguards in place to ensure that operations that may take a long time to complete cannot run on the main thread.

**Comment by kostub** [comment]
We are seeing this in our Xamarin iOS app. When the app loads a lot of data from Parse it freezes for a few seconds while it is parsing the data especially on older phones. 

Would like if we can speed up parsing (maybe use Json.net) or move the parsing to a background thread.

**Comment by TobiasPott** [comment]
This issue should be solved due to improved support for async-await by Unity.
If you encounter any similar problems with the latest version of the SDK feel free to create a new issue to discuss possible solutions.
