### ISSUE TITLE
Change exception messages when using subclass

### ISSUE THREAD

**Issue by davidroberts63** [parse-community/Parse-SDK-dotNET#112]
When just starting out with Parse there are a few things I ran into that would be nice to have a bit more info in the exception messages. It's all clearly in the docs. I simply forgot to do as the docs say. I ended up spending a few minutes trying to figure out what I did wrong. So:
##### When you forget to register your subclass with Parse you get:

"You must create this type of ParseObject using ParseObject.Create() or the proper subclass."

How about changing that to

"You must create this type of ParseObject using ParseObject.Create() or the proper subclass. If it's a subclass remember to ParseObject.RegisterSubclass<>() before Parse.Initialize()."
##### When you forget to add the `ParseClassName` attribute to a subclass of `ParseObject` you get:

"Value cannot be null. Parameter name: key"

How about changing that to

"You must specify the class name of this subclass using the ParseClassName attribute"

I will work on this and send a PR just jotting this down for notes and thoughts.

**Comment by richardjrossiii** [comment]
You're right, these messages could be improved significantly. If you are still interested in taking this over, feel free to, I think most of these messages can be found in `Internal/Object/Subclassing/ObjectSubclassingController.cs`.

If not, just let me know and I'll update them myself.

**Comment by TobiasPott** [comment]
This issue is quite old but the idea itself has a valid point.
I've picked it up and will create a new issue in the next weeks to keep track of it for the latest version and evaluate changes in the current error messages.
If any other messages might need clarification feel free to reach out to us and create a new issue for any suggestions you might have.
