### ISSUE TITLE
Support for additional data types

### ISSUE THREAD

**Issue by davidroberts63** [parse-community/Parse-SDK-dotNET#113]
The ParseObject subclassing does not support the `DateTimeOffset` or `decimal` data types. Any thoughts on implementing that? I'd be willing to work on it and send in a PR.

**Comment by richardjrossiii** [comment]
Neither of these datatypes are supported anywhere in our SDK, although in the case of `decimal` it probably should be possible. Marking as enhancement, but seeing as adding these datatypes isn't exactly trivial, I wouldn't really recommend you to try and go fix them yourself.

I'm not sold on why `DateTimeOffset` should be stored in Parse differently than just something as simple as a number of 'seconds', can you provide an example usage where using `DateTimeOffset` directly provides a tangible benefit?

**Comment by montymxb** [comment]
We have no plan for directly supporting this date types.
