### ISSUE TITLE
Unity doesn't support choosing Push Icon. Necessary for Android SDK >= 21

### ISSUE THREAD

**Issue by alanmgfb** [parse-community/Parse-SDK-dotNET#12]
This is a Feature Request received from the Facebook Bug Tool:
Setting
<meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/push_icon"/>

In the AndroidManifest of a Unity project doesn't actually change the icon.
This developer is complaining because the Android guidelines for Lollipop require 

Full context here: https://developers.facebook.com/bugs/420350694835566/

**Comment by santacrs** [comment]
Our Unity game that uses parse push notification has been selected for Google featuring nomination and this issue has been flagged as a must fix before featuring. If this is not fixed soon it will prevent us from being featured by Google.  Has there been any news with regards to resolving this?

**Comment by hallucinogen** [comment]
Hi there,

This is fixed in Xamarin. We're going to make an internal changes on ParsePush.jar to make it happen on Unity. There'll be no PR sent for this. This should be fixed in .NET SDK 1.6.2

**Comment by henryyGit** [comment]
What is the estimated time for sdk 1.6.2?

**Comment by manelizzard** [comment]
Is there anyway to build the ParsePush.jar for Android while waiting for the official release?

**Comment by hallucinogen** [comment]
Coming with a PR to add `ParsePush.jar` in the repo. Later you'll be able to get it here: https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/Parse.StarterProjects/CSharp/ParseUnityPushSample/Assets/Plugins/Android/ParsePush.jar

**Comment by montymxb** [comment]
Closing as this appears to have been resolved in #75.
