### ISSUE TITLE
Unity webplayer SecurityException with ParseUser.LoginInAsync when not connected to the internet.

### ISSUE THREAD

**Issue by alanmgfb** [parse-community/Parse-SDK-dotNET#13]
Running ParseStarterProject on Unity 5.x without network results in the following error:

SecurityException: No valid crossdomain policy available to allow access
UnityEngine.WWW.get_text ()
Parse.PlatformHooks+<>c__DisplayClass3c+<>c__DisplayClass42.<RequestAsync>b__36 (UnityEngine.WWW www)
Parse.PlatformHooks+<>c__DisplayClass24.<RegisterNetworkRequest>b__23 ()
Parse.PlatformHooks+<RunDispatcher>d__48.MoveNext ()
UnityEngine.Debug:LogException(Exception)
Parse.<RunDispatcher>d__48:MoveNext()

This seems to happen before calling Parse (I guess in the initialization process), so there is no way to catch this exception from the developer.

Original bug report for more context: https://developers.intern.facebook.com/bugs/1630153217241434/

**Comment by montymxb** [comment]
Closing as out of date.
