### ISSUE TITLE
Xamarin Forms + Parse 1.6.2 Component Error 404 and 400

### ISSUE THREAD

**Issue by JodyAndrews** [parse-community/Parse-SDK-dotNET#131]
Hi,

Sorry to ask this as maybe it's covered somewhere but I'm not having much look finding it.

Whenever I make a LoginAsync request, or SignUpAsync (amongst others) if an error occurs (incorrect password, email already exists etc) rather than receive a reason I get either 404 not found or 400 bad request.

I'm sure this used to work in Parse 1.5.5

Example SignUp using an email that already exists

```
        await user.SignUpAsync ().ContinueWith (t => {
            if (t.IsFaulted || t.IsCanceled) {
                Console.WriteLine(t.Exception.InnerException.Message); // 400 bad request
            } else {
                Console.WriteLine("account created");
            }
        });
```

Try Catch ParseException gives nothing back either.

I'm using Xamarin.Forms 2 with shared projects, not PCL. When not intentionally trying to cause an error Parse works fine, can Login, Create, Save etc.

Any ideas on this one?

Cheers

Edit : Actually no sooner I wrote that I find https://www.parse.com/questions/unity-sdk-handling-errors with the exact same problem.

So is this valid for Xamarin too? If so, then this used to work or did I imagine it?

**Comment by richardjrossiii** [comment]
Our networking stack was changed in 1.6.0 and as a result our error reporting is not the same.

We do need to fix this at some point so that we can properly throw `ParseException`s again.

**Comment by JodyAndrews** [comment]
Okay thanks Richard, that's unusable in my case. I'll check out the REST API instead.

**Comment by montymxb** [comment]
Closing as out of date.
