### ISSUE TITLE
Tracking push opens is not supported on Unity now.

### ISSUE THREAD

**Issue by paradizIscool** [parse-community/Parse-SDK-dotNET#143]
Hi all,

We really need this feature in Unity. We really need to track the campaigns and A/B Testing results. We want to make them more efficient. 

Is there a way to do this, without using the Android/IOS Plugin ? Especially Android because of dex limit.

Thanks

**Comment by hallucinogen** [comment]
Thanks for the report. If you're using Parse Push and can receive push already in your Parse Unity SDK-powered app, then the Android Plugin is required whether you track the push open or not (it's only 13KB anyway). This feature is in timeline, but I can't give you a specific timeline for this yet.

**Comment by p0w1nd** [comment]
+1
I've been waiting for this feature too. Thanks.
