### ISSUE TITLE
Initialization during Unity Editor mode

### ISSUE THREAD

**Issue by birdkingz** [parse-community/Parse-SDK-dotNET#150]
Is there any way to allow Parse initialization works properly without hitting the Play button on Unity? 
I want to run it during Editor mode so I can write an Editor to do Parse actions.

PS: Not sure is this a right place to ask about this feature.

**Comment by birdkingz** [comment]
not sure is this a right place to ask about this question...

**Comment by cfoulston** [comment]
Yes. You need a bit of Reflection and an ability to run a Coroutine in the Editor.

Editor Coroutines: https://gist.github.com/benblo/10732554
Start a Coroutine OnEnable on your EditorWIndow or Editor:

```private static IEnumerator GetPlatformHooks() {

			Type t = Type.GetType("Parse.PlatformHooks, Parse.Unity");
			MethodInfo m = t.GetMethod("RunDispatcher", BindingFlags.Static | BindingFlags.NonPublic);

			return m.Invoke(null, null) as IEnumerator;
		}```

You should also stop the Coroutine OnDisable and OnDestroy from your EditorWIndow.

**Comment by richardjrossiii** [comment]
@cfoulston is correct in his approach, if you do that, alongside a call to `ParseClient.Initialize()`, you should be good to go.

**Comment by jeanfabre** [comment]
Indeed, this is a great tip! I also want to use Parse during editing, not just during playback.

**Comment by birdkingz** [comment]
It works like a charm!
Thank you so much!

**Comment by montymxb** [comment]
Closing as resolved and out of date.
