### ISSUE TITLE
Cannot track opened push notification WinRT (UWP too)

### ISSUE THREAD

**Issue by Julien-Mialon** [parse-community/Parse-SDK-dotNET#162]
Hello,

I just looked at the problem referenced there : https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/63#issuecomment-172407281 about the opened count of push notification which stays at 0. 

I tested with WinRT (nuget v1.7.0) and my UWP implementation (https://github.com/ParsePlatform/Parse-SDK-dotNET/pull/91) and when using `ParseAnalytics.TrackAppOpenedAsync(args)`, it expects to have a "push_hash" field in json sent by parse for the notification to track the opening but this field is missing. (Only have `{"alert": "message"}`) I supposed it's an issue with the content sent by Parse backend and not really with the sdk ?

**Comment by richardjrossiii** [comment]
Definitely a bug. As can be seen from https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/Internal/Analytics/Controller/PFAnalyticsController.m#L52-L60, we are supposed to calculate this hash client-side. Fix coming soon.

**Comment by bnham** [comment]
@Julien-Mialon Thank you for your great work on this patch and pointing out this limitation. I think technically it will be cleaner to address this slightly differently though as I'll point out below.

@richardjrossiii I think we should fix this on the server side by sending the push_id directly down to windows devices (we already do this in the Android SDK). Push hash was a mistake/limitation from the iOS SDK--the original idea was that APNs could only handle 256B messages, we didn't want to use up any of the dev's valuable push payload space for something like an identifier, so we instead calculated the identifier by hashing the "alert" portion of the payload. This isn't really an issue anymore now that APNs payloads can be much larger, and Windows doesn't really have this limitation, so we shouldn't spread push_hash to any new platforms as it was a hack to begin with.

Ping me tomorrow about this so we can collaborate on the server side changes needed to make this possible.

**Comment by montymxb** [comment]
Closing as parse.com is no longer running.
