### ISSUE TITLE
Too Many Open Files exception thrown from in Parse.PlatformHooks

### ISSUE THREAD

**Issue by gusennan** [parse-community/Parse-SDK-dotNET#163]
In Xamarin.IOS, I call:

``` cs
ParseUser.LogOutAsync()
```

The method `System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile` fails with a too-many open files error, and the app crashes.

On subsequent launches, the app tries to load the saved JSON file from IsolatedStorage, but this file was corrupted on the last save, and the app crashes immediately with:

```
System.ArgumentException: Input JSON was invalid.
      at Parse.Internal.Json.Parse (System.String input) [0x0003c] in <filename unknown>:0 
```

The attached files are exception logs corresponding to the first and second issues noted above:

[Parse_InvalidJSONException.txt](https://github.com/ParsePlatform/Parse-SDK-dotNET/files/95729/Parse_InvalidJSONException.txt)
[ParseService_TooManyOpenFiles.txt](https://github.com/ParsePlatform/Parse-SDK-dotNET/files/95730/ParseService_TooManyOpenFiles.txt)

**Comment by montymxb** [comment]
Closing as out of date.
