### ISSUE TITLE
Expose ParseUser.SessionToken in the public API

### ISSUE THREAD

**Issue by kostub** [parse-community/Parse-SDK-dotNET#165]
The SessionToken is currently exposed as an internal function. But it is useful to pass the SessionToken to the BecomeAsync(string sessionToken) function to log in as a particular user.

Both the iOS and Javascript APIs already expose the sessionToken, so the .NET API should as well.

**Comment by TobiasPott** [comment]
This is solved and was implemented in the past.
Unfortunately this issue never received an update on this but the SessionToken of an ParseUser instance is publicly accessible.
