### ISSUE TITLE
Exception:  Android.Content.PM.PackageManager+NameNotFoundException: ComponentInfo{com.company.product/parse.ParsePushService}

### ISSUE THREAD

**Issue by jaganjan** [parse-community/Parse-SDK-dotNET#167]
# When i intialize the parse sdk i got this  error

  ParseClient.Initialize(SocialKeyHelper.ParseApplicationId, SocialKeyHelper.ParseDontNetKey);
   LoadApplication(new App())

**Comment by jaganjan** [comment]
Environment details

Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA463
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA463
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA463
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   5.0.15325.0
GhostDoc automatically generates XML documentation comments.

GitHub Extension   0.5
Allows you to work with GitHub repositories and issues from within Visual Studio

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 10.0.2   Build 104.0.20151218.120627
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

SQLPromptVsPackage   1.0
Information about my package

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

Xamarin   4.0.1.89 (413372c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.1.10 (e98e962)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.4.1.24 (47eb74b)
Visual Studio extension to enable development for Xamarin.iOS.

XamlStylerVSPackage   1.0
Xaml Styler.

**Comment by richardjrossiii** [comment]
If I had to guess, you're missing a relevant section in your app manifest about push notification services. Follow the guide at https://parse.com/apps/quickstart#parse_push/android/native/existing.

**Comment by jaganjan** [comment]
Here is my Full implementation

My manifest XML


```
<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0"
          package="ca.xxx.xxx" android:installLocation="auto">
  <uses-sdk android:minSdkVersion="19" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <uses-permission android:name="ca.appguys.xxxx.permission.C2D_MESSAGE" />

  <uses-permission android:name="android.permission.GET_ACCOUNTS" />


  <permission android:protectionLevel="signature"
              android:name="ca.xxx.xxx.permission.C2D_MESSAGE" />
  <application android:label="xxxx" android:theme="@style/NoActionBarTheme" android:icon="@drawable/Icon"
               android:largeHeap="true">


    <activity android:name="com.facebook.FacebookActivity"
              android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
              android:label="@string/app_name" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />
    <meta-data
      android:name="com.parse.APPLICATION_ID"
      android:value="@string/parse_app_id" />
    <meta-data
      android:name="com.parse.CLIENT_KEY"
      android:value="@string/parse_client_key" />
    <service android:name="com.parse.PushService" />
    <receiver android:name="com.parse.ParsePushBroadcastReceiver"
              android:exported="false">
      <intent-filter>
        <action android:name="com.parse.push.intent.RECEIVE" />
        <action android:name="com.parse.push.intent.DELETE" />
        <action android:name="com.parse.push.intent.OPEN" />
      </intent-filter>
    </receiver>
    <receiver android:name="com.parse.GcmBroadcastReceiver"
              android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

        <category android:name="ca.xxx.xxx" />
      </intent-filter>
    </receiver>
  </application>
</manifest>
```

My activity 

` ParseClient.Initialize(SocialKeyHelper.ParseApplicationId, SocialKeyHelper.ParseDontNetKey);`

**Comment by richardjrossiii** [comment]
Thanks! I'll look into it.

**Comment by jaganjan** [comment]
**_More information about MY environment ._**

**_OS DETAILS_**

Microsoft WINDOWS  10 PRO X64

**_IDE DETAILS_**

```
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA463
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA463
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA463
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub Extension   0.5
Allows you to work with GitHub repositories and issues from within Visual Studio

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 10.0.2   Build 104.0.20151218.120627
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

SQLPromptVsPackage   1.0
Information about my package

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

Xamarin   4.0.1.93 (c7ebc0f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.1.10 (e98e962)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.4.1.24 (47eb74b)
Visual Studio extension to enable development for Xamarin.iOS.
```

**Comment by jaganjan** [comment]
what is going on are you replicate this issue? @richardjrossiii

**Comment by kentcb** [comment]
Have this same issue. In my case, using Xamarin Android.

It's been months. Can we have an update @richardjrossiii ?

**Comment by kentcb** [comment]
@jaganjan did you manage to move past this problem?

**Comment by kentcb** [comment]
Ugh, it's not actually a second-chance exception. I had break on exceptions enabled, so was getting thrown by this. It would be nice if the SDK didn't throw internally like this because it makes life more difficult for consuming developers.

**Comment by montymxb** [comment]
Closing as out of date.

**Comment by sinclas** [comment]
Hi,

I am getting this issue with a Droid project in a Forms PCL.   The initialize method is throwing this error.  Works fine for the iOS project in the same solution.  Did anybody come across this recently?  I am using VS on MAC (7.3.3) and loaded the Parse 1.7.0 version into the packages.  

Any ideas?

**Comment by montymxb** [comment]
Hey we're bumping along to a 2.0 alpha atm. The old design is currently
being revamped around the core, which will then be extended to support
additional platforms again.

We're not providing active support for 1.7 as a result. Apologies if this
is causing a problem...in time we expect the new sdk design will serve to
be a better approach than maintaining the old one.

**Comment by z-shaikh** [comment]
Facing the same error into Xamarin.Android on 

                ParseClient.Initialize(new ParseClient.Configuration
                {
                    ApplicationId = ServerConf.AppName,
                    Server = ServerConf.ServerAddress
                });
                
                //Exception: Android.Content.PM.PackageManager+NameNotFoundException: ComponentInfo{com.company.product/parse.ParsePushService}
                
  
Did anyone found a solution for this or any workarounds?
 @jaganjan  @montymxb @kentcb @sinclas @richardjrossiii any help or a direction would be appreciated.
