### ISSUE TITLE
Updating ParseACL on an object doesn't work

### ISSUE THREAD

**Issue by kostub** [parse-community/Parse-SDK-dotNET#173]
I have the following code:

```
        bool isPublic = true;
        problem.ACL.PublicReadAccess = isPublic;
        problem.ACL.PublicWriteAccess = isPublic;
```

We have problem.ACL as not null and in the debugger I can see that the values in the ACL are updated correctly. However when the object is saved, the ACL is not saved on the server.

The work around for it is to always create a new ACL object:

```
        bool isPublic = true;
        problem.ACL = new ParseACL(problem.Owner);
        problem.ACL.PublicReadAccess = isPublic;
        problem.ACL.PublicWriteAccess = isPublic;
```

In this case the ACL gets saved correctly. 

I am using Parse 1.7.0.

**Comment by montymxb** [comment]
Closing as this is likely a non-issue, or an early issue with open source parse-server. We should tests that will account for this behavior, if not already present.
