### ISSUE TITLE
(Some) Relational Queries Fail on iOS when using IL2CPP

### ISSUE THREAD

**Issue by skumancer** [parse-community/Parse-SDK-dotNET#176]
I'm on the process of moving our game to IL2CPP to support 64-bit, but we've hit a wall I just can't bypass.

On Mono 2.0, Relational Queries work properly, when on IL2CPP, some of my queries just plain fail, without a hint of why. They don't return or error out, they just disappear.

I can provide access to our project in case it's necessary.

Example data:

Parse Class: ActivityDataModel
Query: Props of type ParseQuery<PropDataModel>

` public void LoadProps()
    {
        if (!UsingLocalCache)
        {
            Debug.LogFormat("[ActivityDataModel]: Getting props for activity {0}. Query is {1}", Name, (Props.Query != null ? "valid" : "invalid"));

```
        Props.Query.FindAsync().ContinueWith(task => 
        {
            Debug.LogFormat("[ActivityDataModel]: {0} prop query started", Name);

            try
            {
                if (task.IsCompleted)
                {
                    PropList = new List<PropDataModel>(task.Result);

                    Debug.LogFormat("[ActivityDataModel]: Got {0} props for activity {1}", PropList.Count, Name);

                    foreach (PropDataModel data in PropList)
                    {
                        data.LoadEffects();
                    }
                }

                if (task.IsFaulted)
                {
                    Debug.LogFormat("[ActivityDataModel]: Error getting props for activity {0}", Name);

                    foreach (ParseException exception in task.Exception.InnerExceptions)
                    {
                        Debug.LogErrorFormat("[ActivityDataModel]: Parse exception: ({0}){1}", exception.Code, exception.Message);
                    }
                }
            }
            catch (AggregateException exception)
            {
                Debug.LogErrorFormat("[ActivityDataModel]: {0}", exception.Message);

                foreach (Exception e in exception.InnerExceptions)
                {
                    Debug.LogErrorFormat("[ActivityDataModel]: {0}", e.Message);
                }
            }
        });
    }
}`
```

After this, the output:

[ActivityDataModel]: Getting props for activity Boxing. Query is valid
...
...
[ActivityDataModel] Getting Jump Rope prop for level 1. PropList is invalid

There is ample time (about 1 minute) between these two lines, which is enough in Mono 2.0 to get the query information back. I can even let it go for 10 minutes and it won't return or error out. There is just no response from the query.

**Comment by skumancer** [comment]
A little more information, here's what happens when loading starts

[TutorialDatamodel]: Got 0 steps for tutorial 103
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.Debug:LogFormat(String, Object[])
TutorialDataModel:<LoadSteps>m__99(Task`1)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass1:<ContinueWith>b__0(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass8:<ContinueWith>b__7(Task)
System.Func`2:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task`1:RunContinuations()
System.Threading.Tasks.Task`1:TrySetResult(T)
System.Threading.Tasks.TaskCompletionSource`1:TrySetResult(T)
System.Threading.Tasks.<>c__DisplayClass7`1:<Unwrap>b__6(Task`1)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass1:<ContinueWith>b__0(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass8:<ContinueWith>b__7(Task)
System.Func`2:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task:ContinueWith(Func`2, CancellationToken)
System.Threading.Tasks.Task:ContinueWith(Action`1, CancellationToken)
System.Threading.Tasks.Task:ContinueWith(Action`1)
System.Threading.Tasks.Task`1:ContinueWith(Action`1)
System.Threading.Tasks.<>c__DisplayClass7`1:<Unwrap>b__5(Task`1)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass1:<ContinueWith>b__0(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass8:<ContinueWith>b__7(Task)
System.Func`2:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task`1:RunContinuations()
System.Threading.Tasks.Task`1:TrySetResult(T)
System.Threading.Tasks.TaskCompletionSource`1:TrySetResult(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task`1:RunContinuations()
System.Threading.Tasks.Task`1:TrySetResult(T)
System.Threading.Tasks.TaskCompletionSource`1:TrySetResult(T)
System.Threading.Tasks.<>c__DisplayClass7`1:<Unwrap>b__6(Task`1)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass1:<ContinueWith>b__0(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass8:<ContinueWith>b__7(Task)
System.Func`2:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task:ContinueWith(Func`2, CancellationToken)
System.Threading.Tasks.Task:ContinueWith(Action`1, CancellationToken)
System.Threading.Tasks.Task:ContinueWith(Action`1)
System.Threading.Tasks.Task`1:ContinueWith(Action`1)
System.Threading.Tasks.<>c__DisplayClass7`1:<Unwrap>b__5(Task`1)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass1:<ContinueWith>b__0(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass8:<ContinueWith>b__7(Task)
System.Func`2:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task`1:RunContinuations()
System.Threading.Tasks.Task`1:TrySetResult(T)
System.Threading.Tasks.TaskCompletionSource`1:TrySetResult(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task`1:RunContinuations()
System.Threading.Tasks.Task`1:TrySetResult(T)
System.Threading.Tasks.TaskCompletionSource`1:TrySetResult(T)
System.Threading.Tasks.<>c__DisplayClass7`1:<Unwrap>b__6(Task`1)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass1:<ContinueWith>b__0(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass8:<ContinueWith>b__7(Task)
System.Func`2:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass5:<ContinueWith>b__2()
System.Action:Invoke()
System.Threading.Tasks.Task:<.cctor>b__23(Action)
System.Action`1:Invoke(T)
System.Threading.Tasks.<>c__DisplayClass3`1:<ContinueWith>b__1(Task)
System.Action`1:Invoke(T)
System.Threading.Tasks.Task:ContinueWith(Func`2, CancellationToken)
System.Threading.Tasks.Task:ContinueWith(Action`1, CancellationToken)
System.Threading.Tasks.Task:ContinueWith(Action`1)
System.Threading.Tasks.Task`1:ContinueWith(Action`1)
System.Threading.Tasks.<>c__DisplayClass7`1:<Unwrap>b__5(Task`1)

**Comment by richardjrossiii** [comment]
It's very difficult to tell what's going on here. Can you show me how your queries are being created?

**Comment by skumancer** [comment]
@richardjrossiii all we do is have a property that defines a query, and then execute it

`[ParseFieldName("Props")]
public ParseRelation<PropDataModel> Props
{
	get { return GetRelationProperty<PropDataModel>("Props"); }
}`

`Props.Query.FindAsync().ContinueWith(task => 
{}`

**Comment by montymxb** [comment]
Closing as no further details were provided.
