### ISSUE TITLE
get_isWebPlayer can only be called from the main thread.

### ISSUE THREAD

**Issue by cfoulston** [parse-community/Parse-SDK-dotNET#179]
When compiling with Unity and calling User.FetchAsync

**Comment by sghamaty** [comment]
Im getting the same error in Unity. Its better to put these functions in a constant somewhere.

This blocks Unity apps from Migrating away from the Parse service and on to the Open Source version.

> get_isWebPlayer can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

**Comment by richardjrossiii** [comment]
@sghamaty Currently, we only use `isWebPlayer` for our storage implementation, and I have a few thoughts on how to make this work. I'll let you guys know as soon as I get the solution working for this.

**Comment by sghamaty** [comment]
@richardjrossiii I dont think were doing anything specific to turn on the storage implementation. Is there any way to disable it?

**Comment by richardjrossiii** [comment]
@sghamaty It's used to store the current user and installation on device so you don't have to re-log in. I need to make isWebPlayer a cached property on Dispatcher eventually, I think. If you really wanted to, and you're not targeting the web player, you could just comment out those relevant lines in [StorageController.cs](https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/f577ee38a0d55a199a473065b18acad084e4b083/ParseCommon/Internal/Storage/Unity/StorageController.cs#L58)

**Comment by sghamaty** [comment]
That makes sense.

We will need to support web, so we'll need to figure out the long term fix.

Till then I'll see if we can work around as you suggested.

**Comment by chris3000** [comment]
Is this still an open issue? I'm seeing this same error on login and signup. I'll try to find the relevant lines in StorageController but this seems like a showstopper bug for migrating over to our own parse servers.

**Comment by cleyden** [comment]
This is still a problem, anyone had any luck with a work around?

**Comment by kenglou** [comment]
why not tried to use back the old method and use 

> Application.platform == RuntimePlatform.WebGLPlayer

 to do the checking?

**Comment by montymxb** [comment]
Marking as an outstanding issue that we'll take a look at.

**Comment by TobiasPott** [comment]
This issue is solved with the latest version available form the master branch.
The SDK now allows changing the behaviour with custom mutators specific to your platform and not rely on any modular assemblies to handle Unity specific environments.
