### ISSUE TITLE
Registering Subclasses (IndexOutOfRangeException)

### ISSUE THREAD

**Issue by alexpwer** [parse-community/Parse-SDK-dotNET#180]
Failed to postprocess stacktrace
IndexOutOfRangeException: Array index is out of range.
  at Parse.Internal.ParseCorePlugins.get_SubclassingController () [0x00000] in <filename unknown>:0 
  at Parse.ParseObject.RegisterSubclass[T]() [0x00000] in <filename unknown>:0 
  at ParseManager.Awake () [0x00000] in <filename unknown>:0 

(Filename: currently not available on il2cpp Line: -1)

It's referencing the following method:

void Awake()
 {
        ParseObject.RegisterSubclass< Team >();
        ParseObject.RegisterSubclass< Player >();
        ParseObject.RegisterSubclass< Fixture >();
}

It's been working fine until recently. I'm using Unity 5.3.2p1 and Parse Unity 1.7.0.

**Comment by richardjrossiii** [comment]
Can you share the definitions of all of your ParseObject subclasses?

**Comment by montymxb** [comment]
Closing as no further details provided.
