### ISSUE TITLE
Random select document

### ISSUE THREAD

**Issue by abraaocaldas** [parse-community/Parse-SDK-dotNET#181]
Hello, I saw a lot of people asking for a way to get a random document from a table, from mongodb 3.2  this is now possible using $sample. there is any way to implement it on Parse SDK?

Using:
{ $sample: { size: <positive integer> } }

PS: I tried to implement it on parse SDK but I cannot get past some compile errors like: "You cannot use portable blah blah blah"

**Comment by abraaocaldas** [comment]
Any news about this?

**Comment by montymxb** [comment]
There is no intent to implement this, closing this out.
