### ISSUE TITLE
unity win phone 10 deploy: ios notification stuff error in il2cpp deploy

### ISSUE THREAD

**Issue by UgurIster** [parse-community/Parse-SDK-dotNET#193]
So i'd like to deploy a unity app to win phone 10 using il2cpp as backend since that is supposed to allow using more of the mono C# api than when deploying with mono backend but when trying that then on deploy attempt it throws an error stating:

System.Exception: Error processing method: 'System.Void Parse.PlatformHooks/<>c__DisplayClass28::<RegisterDeviceTokenRequest>b__26()' in assembly: 'Parse.Unity.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Byte[] UnityEngine.iOS.NotificationServices::get_deviceToken()

so it looks like when doing win phone 10 deploy wih il2cpp setting then in the Parse Unity dll it goes into iOS specific code.

**Comment by richardjrossiii** [comment]
We don't technically support windows phone via unity, as it will fail due to tasks existing already as well. We're in the process of modularizing the SDK to allow support of windows platforms, but there's still a good amount of work to be done until we can support this.

**Comment by UgurIster** [comment]
Cool regarding modularizing the sdk, regarding technically not supporting windows phone, well, i thought in il2cpp deploy more of the mono C# api is supported for win 10 universal deploy than with C# backend setting hence why i tried that as work around. The error i got there to me sounds like it would maybe just need a platform dependent compiler flag like #if UNITY_IPHONE around that code block there since right now it seems to go into iOS specific code there for notifications when deploying to win 10 universal with il2cpp setting

**Comment by richardjrossiii** [comment]
@UgurIster FWIW, on master you should be able to use Parse without Push, if you have access to Visual Studio (building the SDK from Xamarin is currently not supported).

**Comment by montymxb** [comment]
Closing as we don't plan on necessarily supporting this.
