### ISSUE TITLE
Unable to use extra GCM sender

### ISSUE THREAD

**Issue by unger** [parse-community/Parse-SDK-dotNET#194]
When adding the following to the AndroidManifest

`<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:1234" />`

You get the following row in logcat: 

`Found com.parse.push.gcm_sender_id <meta-data> element with value "id:1234", but the value is missing the expected "id:" prefix`

The message sounded a bit strange as the value indeed had a id: prefix. When looking at the code in ParsePush\Internal\Android\GcmRegistrar.cs on line 38 the check against if senderIdExtra is a string fails because it really is of type Bundle. There is also a problem on row 65 where senderIds is concatenated with senderIdExtra that still has the id: in the string, it should concatenate with senderId instead.

**Comment by richardjrossiii** [comment]
Good find. Feel free to send a PR to fix, otherwise I'll get to it at some point before the next release.
