### ISSUE TITLE
Question: How to get the data passed on Push

### ISSUE THREAD

**Issue by brilvio** [parse-community/Parse-SDK-dotNET#206]
Sorry if I am a moron, but I cannot find a Example in C# I tried the examples from java but the Intent.Extras is always null and Intent.GetStringExtras(); I tried with every possible string and the result is always null.

I use a modified version of tag 1.7.0, because the release 1.7.0 doesn't work with custom GCMSenderId.

**Comment by montymxb** [comment]
Closing as we're consolidating prior issues. If this is still a problem let us know and we'll reopen.
