### ISSUE TITLE
ParseInitializeBehaviour does not have "server" field in Unity.

### ISSUE THREAD

**Issue by noughts** [parse-community/Parse-SDK-dotNET#211]
ParseInitializeBehaviour does not have "server" field in Unity.
It has only "Application ID" and "Dotnet Key" fields.
How can we set our own parse-server URL in Unity?

Environment:
Unity 5.3.4
Parse SDK for .NET 1.7.0
(Downloaded from https://github.com/ParsePlatform/Parse-SDK-dotNET/releases/tag/1.7.0)

**Comment by jjborde** [comment]
How to integrate parse server, running on heroku with Unity Parse SDK ?

**Comment by Avatarchik** [comment]
https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166

**Comment by noughts** [comment]
@Avatarchik 
Thank you. I saw it.
But there are many ZIP files so I can't make a decision which file should we use.

Would you tell me which file is the best for me?
I use Unity 5.3.4 and distribute to both Android and iOS.

Sorry for my poor English. Thanks!

**Comment by kenglou** [comment]
Currently I'm trying to use creating the ParseInitializerBehaviour myself in starting function using following code:

` ParseInitializeBehaviour _script = m_instance.gameObject.AddComponent<ParseInitializeBehaviour> ();
        _script.applicationID = <ApplicationID>;
        _script.dotnetKey = <DotNetKey>;


        ParseClient.Initialize (new ParseClient.Configuration () {
			WindowsKey = <DotNetKey>,
			ApplicationId = <ApplicationID>,
                        Server = <ParseServerPath>
			});`

Hope that helps.

**Comment by noughts** [comment]
@kenglou 
Thanks for your suggestion.
But unfortunately that is not worked in my environment😢

**Comment by noughts** [comment]
@kenglou 
Wow I tried again several times and it works!
The important point:
don't forget last "/" for Server value.

**Comment by kenglou** [comment]
no problem as long as it helps :)

**Comment by mayafishing** [comment]
It really helps! Thanks!

Just wondering why the official Unity SDK does not allow to set the Parse Server URL! It has been a long while! Anyone working on that?

**Comment by AngelKyriako** [comment]
@mayafishing I fixed this app for the app I am working on

https://github.com/AngelKyriako/Parse-SDK-dotNET

once u clone make sure you `git checkout angelkyriako/master`

You may build it with mono or VS

Hope that helps

**Comment by montymxb** [comment]
Closing as we will be working this into the next release and are aware of it.
