### ISSUE TITLE
ParseFile isn't saving images

### ISSUE THREAD

**Issue by chris3000** [parse-community/Parse-SDK-dotNET#213]
I've compiled the latest code from the repo and it seems like ParseFile saving is broken. 
I replaced Parse in a pre-existing app and we noticed that images were getting saved with no data. So I created a blank Unity app that did nothing but save a Parse Object.
Here's the script:

```
public class ParseHello : MonoBehaviour {
    public Texture2D testing;
    // Use this for initialization
    void Start () {
        ParseFile pf = new ParseFile ("testimg.jpg", testimg.EncodeToJPG (100), "image/jpeg");
        ParseObject obj = new ParseObject ("test");
        obj ["hello"] = "hello from unity!;
        obj ["testimg"] = pf;
        obj.SaveAsync ();
        print ("saved!");
    }
}
```

This saves the object to the test class with a file that only contains the following text (and no jpg data).
`{"_method":"POST","_noBody":true}`

Any help would be appreciated!

**Comment by tomh4** [comment]
How did you even compile ? It is throwing a bunch of errors at me

**Comment by chris3000** [comment]
Honestly, it was a bit of trial and error. I'm a mac person but I couldn't get it to compile with Xamarin. I found a Windows machine and installed Visual Studio. I use Parse for Unity so I'm unfamiliar with VS. I had to set .NET to 3.5 and choose the correct solution (which escapes me at the moment) but finally I got a build. I had to follow the instructions [from this issue](https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/179) to get login and sign-up working, and now I'm having trouble with ParseFiles.

In all, I'm confused how the current state of this SDK could be so buggy, considering how relatively stable the last released version (1.6.0) was. I guess it's time to get more comfortable with Visual Studio...

**Comment by tomh4** [comment]
I am not able to use 1.7 to connect to my server it somehow fails... so I wanted to try the master tree (1.8.x) but it fails to compile and the new restructuring confuses me... but there is no support to this sdk anymore imo...

**Comment by thewizster** [comment]
You need to save the parse file object first. Call `await pf.SaveAsync();` on the parse file object before `obj ["testimg"] = pf;`

Take a look at the docs example.
https://parse.com/docs/dotnet/guide#files

**Comment by chris3000** [comment]
I'm using unity so I can pause using a yield to the coroutine. Either way, I'm still getting the same error. I've now tried to save a parseFile to both my internal Parse stack and to back4app (a hosted Parse provider) with the same incorrect results. Here is the test function that I'm running:

```
	private IEnumerator SaveTestImage() {
		byte[] imgbytes = testimg.EncodeToJPG (100);
		print ("byte count = " + imgbytes.Length);
		byte[] stringbytes = System.Text.Encoding.UTF8.GetBytes("Working at Parse is great!");
		print("starting save test image. Frame: "+Time.frameCount+" Time: "+Time.time);
		ParseFile pf = new ParseFile ("testimg.jpg", imgbytes, "image/jpeg");
		ParseFile pf2 = new ParseFile ("texttxt.txt", stringbytes)
		Task task = pf.SaveAsync ();
		while (!task.IsCompleted) {
			yield return null;
		}
		print("saved test ParseImage. Frame: "+Time.frameCount+" Time: "+Time.time);
		Task task2 = pf2.SaveAsync ();
		while (!task2.IsCompleted) {
			yield return null;
		}
		print("saved test text ParseFile. Frame: "+Time.frameCount+" Time: "+Time.time);
		ParseObject obj = new ParseObject ("test");
		obj ["hello"] = "hello from unity!";
		obj ["testimg"] = pf;
		obj ["testText"] = pf2;
		obj.SaveAsync ();
		Task task3 = pf.SaveAsync ();
		while (!task3.IsCompleted) {
			yield return null;
		}
		print("completed save test image. Frame: "+Time.frameCount+" Time: "+Time.time);
	}
```

In both Parse files I see the following text, as before:
`{"_method":"POST","_noBody":true}`

Also, in the Parse Dashboard I see that the names seem to be changed. I would expect the names to be "testing.jpg" and "text txt.txt" but instead they are changed to "img.jpg" and "txt.txt", as seen in this screen grab:

![screen shot 2016-06-24 at 12 13 23 pm](https://cloud.githubusercontent.com/assets/363807/16343612/29dac3ba-3a06-11e6-80ab-1e2bc7d745fa.png)

Any help would be appreciated! This is definitely a blocker for us, and we can't deploy our app until Parse Files are working.

I can probably do a workaround by uploading directly to S3, but I'd rather avoid an extra SDK in my project.

**Comment by thewizster** [comment]
@chris3000 I haven't used Unity so I'm not much help there.

I do have a sample console app that saves to parse-server that you could take a look at. I just modified it to save a parse file.

I am running parse-server (v2.2.13) on my local machine (Windows at the moment). However for file storage on my local dev parse-server I have the Azure storage file adapter installed. I just tested this console app on my local setup and it works saving the file.

Here is the code pattern I am using in the console app.

```
Console.WriteLine("Saving the image to parse-server.");
Task fileContinuationTask = flagImage.SaveAsync().ContinueWith((antecedent) => {
    Console.WriteLine("Finished saving file to parse-server");
});
fileContinuationTask.Wait();

```
Not sure if it would help in your case. Just thought I would pass along the code...

https://github.com/thewizster/parse-server-console/blob/master/ParseServerConsole/Program.cs

**Comment by chris3000** [comment]
Thanks @thewizster . Have you confirmed that this does indeed save a file to your database? The reason I ask is that I've pointed my demo Unity app to an app I have at Parse.com and I'm seeing the same bug. I feel confident that the problem is not on the remote Parse Server side. I've been using Parse with Unity using the last released Unity SDK and it's worked fine. I would continue to use it but the parse.com url is hardcoded into the Component.

**Comment by thewizster** [comment]
@chris3000 Yes, I am saving image files. I've used both the .Net SDK and parse-dashboard to save image files. Both with success.

**Comment by chris3000** [comment]
Hi @thewizster One last question if it's ok: Are you using a particular tagged commit, or are you using the Head of the master branch?

**Comment by thewizster** [comment]
No prob. @chris3000 I am just using the Nuget 1.7.0 package. https://www.nuget.org/packages/parse

I have a couple mobile projects and the .net sample repos on my github using it.

As I understand it, the master branch has modularized and broken the code up a bit. I'm not using that code yet. I have existing code that still uses 1.7.0 so I am sticking with it for the moment.

**Comment by montymxb** [comment]
We'll have to look into this. If the current state of the SDK is problematic we're going to have to make some changes :/.
