### ISSUE TITLE
[Unity3d] Possible to rebuild Parse SDK from Xmarin now?

### ISSUE THREAD

**Issue by kenglou** [parse-community/Parse-SDK-dotNET#214]
as titled. Is Xmarin Problem fixed and abled to build Parse SDK dotnet now?

Or is it possible to use Visual Studio Code to compile the code?

**Comment by richardjrossiii** [comment]
No. Xamarin still fails to find any files when using wildcard search paths in .csproj files :(. You could expand these paths manually, and it should still compile on Xamarin, however.

**Comment by hl4hck** [comment]
@richardjrossiii How to fix it manually?

**Comment by kenglou** [comment]
@richardjrossiii  can you provide more details on how to change search paths in .csproj files? or how to do it in windows? as we can't build ios from windows right? Please advise and thank you.

**Comment by richardjrossiii** [comment]
@kenglou You can build iOS on windows absolutely fine, you will just need to install the proper Xamarin plugin.

But essentially, inside the project file, there is a list of paths to compile:

https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParseCore/ParseCore.Portable.csproj#L40-L45

Wildcard search paths are not supported with mono's build system, for some reason.

If you expanded those paths to include each of the individual files in those directories, it should compile with mono.

**Comment by montymxb** [comment]
Indicating that this is still an outstanding issue. We'll need to address this in such a fashion that it can be built without having to do anything manual...

**Comment by TobiasPott** [comment]
This issue is solved with the latest version available from the master branch.
It works with Xamarin for iOS and Android and the respective platforms using Unity3D.
If you encounter any problems with the latest version feel free to create a new issue to discuss possible solutions.
