### ISSUE TITLE
Problem when creating user subclass (is working with the Unity Asset Store SDK)

### ISSUE THREAD

**Issue by AngelKyriako** [parse-community/Parse-SDK-dotNET#217]
Hello,

This is the exception:

```
ArgumentException: You must create this type of ParseObject using ParseObject.Create() or the proper subclass.
Parse.ParseObject..ctor (System.String className)
Parse.ParseObject..ctor ()
Parse.ParseUser..ctor ()
MemoryCard.Models.BaseNetUserModel..ctor ()
MemoryCard.Models.UserModel..ctor ()
```

it happens when I call something like this:

```
var usr = new UserModel() {
  ObjectId = "someId",
  Username = "someid",
  Firstname = "hello",
  Lastname = "world"
}
```

when the class hierarchy is setup like this:

```
[ParseClassName("_User")]
public class UserModel : BaseNetUserModel {

  public UserModel() { }

}

public abstract class BaseNetUserModel : ParseUser, IDBNetModel {

  public BaseNetUserModel() { }

}

public interface IDBNetModel: IDBModel {
}

public interface IDBModel {
}
```

I have called register only for the UserModel class since I cannot do it for the abstract one:

```
ParseObject.RegisterSubclass<UserModel>();
```

This used to work before I changed the unity asset store sdk to the uploaded sdk here: [https://parse.com/docs/downloads](https://parse.com/docs/downloads)

Any thoughts ?

**Comment by richardjrossiii** [comment]
Hmm. This is probably a bug in https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParseCore/Internal/Object/Subclassing/ObjectSubclassingController.cs, though I'm not 100% sure where. I'd bet that we never tested support for abstract base classes.

Could you perhaps make your base non-abstract? Or maybe add the `ParseClassName` attribute directly to `BaseNetUserModel`?

**Comment by AngelKyriako** [comment]
I for sure tried both but I am not sure what kind of combinations.

Any case the ParseClassName will be needed in all the classes in the class tree related with the _User collection ?

I will try more combinations & I will get back on this

**Comment by richardjrossiii** [comment]
@AngelKyriako I would definitely try it on all classes in the tree. If I had to venture a guess it may have something to do with the logic here: https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParseCore/Internal/Object/Subclassing/ObjectSubclassInfo.cs#L32-L35, where we can't find the attribute if it's inherited only.

**Comment by AngelKyriako** [comment]
@richardjrossiii I tried both and It seems that the issue does not have to do with the abstract class or the fact that the ParseClassName is not defined on all classes in the tree.

It feels like it does not work well when inheriting the ParseUser class, but works when inheriting the ParseObject class.

Currently, I am unable to build the project on my PC. Is there any documentation apart from the start of the README.md in the repository ?

I tried with both the command: MSBuild.exe Parse.sln
and via VS2015.

I also tried to disactivate anything Analytics/Push and Test related in the build configuration in case it helped but nothing.

on windows 10 and vs2015 I get this error multiple times:
File 'Windows.props' not found. See http://go.microsoft.com/fwlink/?prd=12395&pver=1.0&plcid=0x409&ar=MSDN&sar=PlatformMultiTargeting&o1=C:\Program Files (x86)\Microsoft SDKs\Portable\v12.0&o2=Portable for more information.	AssemblyLister.Portable

which I guess is a problem with my setup and will try to resolve.

In the mean time let me know if there is any progress with this issue.

Cheers

**Comment by AngelKyriako** [comment]
@richardjrossiii  after a long time it was about time to deal with this issue.

As I could not build the current master branch I checkout to 1.7.0 to be able to build the plugin.
Therefore I am not sure if I should pull request it on master.

Eventually, the problem is that when creating a new object with the subclass feature, parse will use a dictionary to lookup the type of the subclass registered by class name.

```
   ObjectSubclassInfo subclassInfo;
   registeredSubclasses.TryGetValue(className, out subclassInfo);
```

However, this dictionary keeps only one type per subclass. The method ```public void RegisterSubclass(Type type);``` is made with the logic of keeping the most abstract class in a subclass hierarchy.

That means that in the code below, the dictionary will keep the type ```SomeModel``` as the type mapped to class name ```Model```:
```
[ParseClassName("Model")]
public SomeModel: ParseObject { }

[ParseClassName("Model")]
public SomePlayerModel: SomeModel { }
```
which will fail when calling ```new SomePlayerModel();```

On these lines https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParseCore/Internal/Object/Subclassing/ObjectSubclassInfo.cs#L32-L35
I updated the logical expression to:

```
return subclassInfo == null
   ? type == typeof(ParseObject)
   : subclassInfo.TypeInfo.Equals(type.GetTypeInfo()) || subclassInfo.TypeInfo.IsSubclassOf(type);
```
which makes my Unity code work since I do not have more than 2 level deep subclasses.
I also removed the [ParseClassName("ClassName")] lines from classes that were lower in the hierarchy for clarity.

However, even with this fix added and create an even deeper subclass would throw the exception since
```subclassInfo.TypeInfo.IsSubclassOf(type)``` will return false for a super class 2 levels up.
```
public SomeOtherPlayerModel: SomePlayerModel { }
```
Maybe it would be better to have the ```registeredSubclasses``` dictionary mapped to an array of types and then lookup into that array during type checking for type equality. This seems to be a more proper solution.

Please update the readme regarding building and unit testing the sdk if you want a pull request on that.

Thanks for the help

**Comment by montymxb** [comment]
Marking for further inspection.

**Comment by TobiasPott** [comment]
Due to my experiences with the SDK in the past two years it is possible to use subclassing of ParseObject within Unity.
It might behave differently on mobile or other platforms where Unity code stripping kicks in and removes unused code to speed up compilation (e.g. IL2CPP) 

I close this issue for now, feel free to open a new issue when you encounter any problems with the latest version of the SDK (2.0 or newer)
