### ISSUE TITLE
Updated nuget package?

### ISSUE THREAD

**Issue by AndrewLane** [parse-community/Parse-SDK-dotNET#218]
Looks like 1.7.0 is the latest nuget release, but it's behind master by a couple of months.  Any plan to push the latest out to NuGet?

**Comment by richardjrossiii** [comment]
Master is not currently in a release-ready place. It's missing some core logic required to migrate our old user storage model to our new one (based on PCLFile). This means that if an existing app was to upgrade to the latest SDK version, all of their users (especially anonymous users) would be logged out.

Master is also currently missing the logic for the Facebook and Twitter utils right now.

**Comment by iwansanders** [comment]
It looks like this SDK has not the priority it deserves windows UWP runs great on the Raspberry Pi which makes it an excellent platform for IoT related projects. I would really like to see some "movement" on this branch.

**Comment by kitkat14** [comment]
The NuGet really needs a update it has allot of issues especially push related nothing works out of of the box. Documentation is saying one thing but in practice it will take hours if not days to figure out that the documentation and old nugget are not in sync.

**Comment by johnnydimas** [comment]
I would really like to see a new nuget version published as well. Just spent some time setting up push on our server and on iOS, only to realize it doesn't even work in android.

**Comment by FlorianSchuler** [comment]
@richardjrossiii 
Is still anybody working on this Parse SDK for .NET and will there progresses in future, regarding all the open important issues, or ist this whole project dead and we should look for other services to replace parse?

**Comment by montymxb** [comment]
@FlorianSchuler it's been some time but we will be working on a new release coming up. I won't make any timeframes, as there is quite a lot to go over since this was last updated.

**Comment by montymxb** [comment]
Closing as we are now actively working on preparing for a **1.8.0** release. Further work is still needed but you can ping me if anything in particular comes to mind.
