### ISSUE TITLE
Unable to Receive Push Notifications when App is closed

### ISSUE THREAD

**Issue by amplebrain** [parse-community/Parse-SDK-dotNET#225]
Hi there,

I was finally able to get my parse-server and Unity SDK working. The last piece of the puzzle is fixing push notifications for Android.

So far, It works when the app is opened or in the background but throws an error when the app is is in the background.

> 07-29 15:52:24.781  3522  3537 W Unity   : Native libraries not loaded - dropping message for ParseInitializeBehaviour.OnPushNotificationReceived

My Manifest file is:

```
    <service android:name="com.parse.ParsePushService" />
        <receiver android:name="com.parse.ParsePushBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.RECEIVE_BOOT_COMPLETED" />
                <action android:name="android.intent.action.USER_PRESENT" />
                <category android:name="com.xxxx.xxxxx" />
            </intent-filter>
        </receiver>
```

<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:882389752921" 

> />

I think this is an issue with how the Parse Plugin handles Notifications from GCM but I cant seem to place my finger on the issue. Can someone please have a look?

**Comment by robtaireeo** [comment]
I believe you need to add a GCM broad cast receiver.

**Comment by kitkat14** [comment]
Just forget about using .net parse with parse server push is not working if its closed. the broad cast receiver methods are not working.

Till this is fixed its not a good idea to use. Reversing everything back to normal parse hope that in the coming half year the sdk is updated to be used properly with parse server

**Comment by spl0k** [comment]
I was getting the same issue and managed to fix it by changing the code of the *ParsePush.jar* a bit. What you got to do is simply change the initial value of `applicationPaused` in [ParsePushUnityHelper.java](https://github.com/parse-community/Parse-SDK-dotNET/blob/master/ParsePush/Native/src/main/java/com/parse/ParsePushUnityHelper.java#L34) from `false` to `true`.

Here is the compiled jar: [ParsePush.zip](https://github.com/parse-community/Parse-SDK-dotNET/files/957707/ParsePush.zip)
Tested with Unity 5.5.2 and a *Parse.Unity.dll* downloaded from #166

**Comment by montymxb** [comment]
Push is working fine, it has also change _a lot_ since the server was first made available as OSS. Marking as this needs followup and may be a potential bug in this sdk, independent of the server.
