### ISSUE TITLE
Problem with login and ParseUser.CurrentUser

### ISSUE THREAD

**Issue by tchantchoj** [parse-community/Parse-SDK-dotNET#226]
Hi,

I'm currently building a website using the Parse SDK for .NET

I use the method ParseUser.LogInAsync to log users on my website.

When I login on my website, if I send the link to my website to someone else, he will be automatically logged in as me. Is this normal?

Thanks for your help!

**Comment by montymxb** [comment]
No this should not be happening. As far as details go there's not to much to go on, but since I haven't checked to verify this is _not_ happening I'll flag it for investigation.

**Comment by SeloSlav** [comment]
Any updates on this? I'm experiencing the same problem. @tchantchoj, where are you logging your user in? Are you using ASP.NET MVC Core or RazorPages?

**Comment by SeloSlav** [comment]
@tchantchoj Thanks for the reply. However, now that I think about it I don't this is an "issue" per se as much as something that was just never developed properly for the browser. If you use the SDK in a native mobile app, such as one developed by Xamarin, it will probably work.

**Comment by tchantchoj** [comment]
Hi @SeloSlav,

Thanks for the reply. It might explain why then.

I'm going to go ahead and close this issue.

**Comment by SeloSlav** [comment]
It seems like developers are creating ParseUser libraries based on AspNet.Identity. There is likely no functionality currently in this SDK for storing users in session on web browsers in general. https://www.nuget.org/packages/Parse.AspNet.Identity/
