### ISSUE TITLE
Parse Cloud Issue Push Notification not Received on device

### ISSUE THREAD

**Issue by essamghonim** [parse-community/Parse-SDK-dotNET#232]
I had an issue with pushing notification to ios devices. Having set up the parse cloud function as shown below:
<img width="641" alt="screen shot 2016-09-03 at 03 51 22" src="https://cloud.githubusercontent.com/assets/19748027/18222028/2f44c746-7193-11e6-87a0-a752f595d3de.png">

This is my index.js file:
<img width="576" alt="screen shot 2016-09-03 at 03 52 11" src="https://cloud.githubusercontent.com/assets/19748027/18222030/34ce0a74-7193-11e6-9f3e-0d1d428a42f9.png">

Heroku Log states that the notification was sent to 2 installations but none of the two devices receive any notification. Any sort of help would be really appreciated.
<img width="736" alt="screen shot 2016-09-03 at 03 50 58" src="https://cloud.githubusercontent.com/assets/19748027/18222032/3d6ad18a-7193-11e6-9384-1ed7db77f136.png">

**Comment by montymxb** [comment]
Push notifications have changed quite a lot server-side since late 2016. Closing this out for now. If this is still an issue please check this against later versions of parse-server and let us know whether the problem persists.
