### ISSUE TITLE
How to authenticate a user in Parse dotNET / Unity SDK using OAuth?

### ISSUE THREAD

**Issue by hl4hck** [parse-community/Parse-SDK-dotNET#236]
Hi, Parse Server offers OAuth authentication. The Parse Server docs give examples on how to configure the OAuth modules. e.g. Google.

But, Parse Unity sdk has a ParseUser.LogInAsync("myname", "mypass") method.
I could not find a method like ParseUser.LogInAsync(string authType,...).

How do I use it in dotNET(especially Unity3d) using OAuth to login or signup a user?

**Comment by hl4hck** [comment]
It seemed that Parse dotNET SDK does not support OAuth function, so I got “sessionToken” from Parse-Server by using Parse REST API.
And then, I called ParseUser.BecomeAsync in order to get ParseUser with “sessionToken”, however, it does not work.

How can I use OAuth function in the Parse dotNET SDK?

**1. POST /parse/users** 
```
X-Parse-Application-Id: app_id_**********
Content-Type: application/json
Host: **********.azurewebsites.net 
{
  "authData": {
    "facebook": {
      "access_token": "**********",
      "id": "**********"
    }
  }
}
```

**2. Response**
```
{
  "objectId": "eHDPFoR3E3",
  "username": "aJbGbHtWOW4MuDG3Tc2nzYyzt",
  "authData": {
    "facebook": {
      "access_token": "**********",
      "id": "**********"
    }
  },
  "createdAt": "2016-09-29T13:33:40.749Z",
  "updatedAt": "2016-09-30T00:25:24.836Z",
  "ACL": {
    "*": {
      "read": true
    },
    "eHDPFoR3E3": {
      "read": true,
      "write": true
    }
  },
  "sessionToken": "r:048a7b7d3cfa7e47ce1b7eead73f5798"
}
```

**3. ParseUser.BecomeAsync** 
```
// sessionToken: "r:048a7b7d3cfa7e47ce1b7eead73f5798"
ParseUser.BecomeAsync(sessionToken).ContinueWith(task=>{
 	// not called
	if (task.IsFaulted || task.IsCanceled) {
		foreach(var error in task.Exception.InnerExceptions) {
			ParseException parseException = (ParseException) error;
			Debug.LogWarning("Error message " + parseException.Message + ", Error code: " + parseException.Code);
		}
	} else {
		Debug.Log("ParseUser.BecomeAsync ok");
	}
});
```

**Comment by montymxb** [comment]
3rd party authentication mechanisms are something we have, but they are select (like for facebook). There are quite a few 3rd party auth mechanisms available in parse-server now. I agree that it would be nice to have a general login method with an auth type passed, we have something very similar for the php-sdk that is the base for any directly callable 3rd party authentication mechanisms.

**Comment by TobiasPott** [comment]
In contrast comment by @montymxb third-party auth methods are no longer provided by the Parse SDK itself.
I close this issue as other methods are not currently on any roadmap I'm aware of.
If you consider this important and can provide details and information of possible ways to implement them, feel free to create a new issue to discuss the topic.
