### ISSUE TITLE
[Unity] - Save locally if internet connection is not available

### ISSUE THREAD

**Issue by ZenithCode** [parse-community/Parse-SDK-dotNET#242]
Hey,

Is there a way to save locally in Unity on Android/iOS if internet connection is poor/missing?

I see there's 'SaveEventually' API on some other SDKs.

Regards,

**Comment by montymxb** [comment]
If you're talking about having a local datastore for pending changes that could be interesting...Have a way to delay save ops and submit them later upon reconnect. For now closing this out as there hasn't been any interest in this. If this is still something you're interested in let us know and we can open this up with a little discussion.
