### ISSUE TITLE
Increment value of parse object without saving whole thing

### ISSUE THREAD

**Issue by miracle7** [parse-community/Parse-SDK-dotNET#244]
I would like to increment one value of a parse object and have that change reflected on the server without the whole object being saved, since the cached version of the object on the client may not be up to date.

    tournament.Increment("prizePool", amount);
    tournament.SaveAsync();

Is there any easy way to do this, or do I just have to be sure to always fetch the current version immediately before changing it?

**Comment by montymxb** [comment]
Closing as this is likely a non-issue. Saving an object only transfers the changes made. Out of date objects aside if all you're doing is incrementing and saving, the only changes being transmitted are the single increment (assuming you haven't already saved the object before). You should be fine.
