### ISSUE TITLE
Log spam and stuttering if logged into facebook without internet connection

### ISSUE THREAD

**Issue by miracle7** [parse-community/Parse-SDK-dotNET#247]
We are using the Facebook Unity and Parse .NET SDKs in our mobile app, developed in Unity for Android and iOS.

To reproduce:
- Login to Facebook (using `ParseFacebookUtils.LogInAsync`)
- Close app
- Disable internet connection
- Open app

User is still 'logged in', but the apps framerate drops drastically until internet is enabled, and constantly spams out this in the android logs (using a Samsung Galaxy s6):

`I/System.out(1430): (HTTPLog)-Static: isSBSettingEnabled false`

Logging out of Facebook doesn't help either, seems to happen in old versions of the app too.
None of this happens in the Facebook sample app, only when Parse is involved.

**Comment by miracle7** [comment]
Just been informed this is only happening on Android, iOS is unaffected.

**Comment by montymxb** [comment]
Thanks for providing some basic steps to reproduce. If we eventually start going over the possibility of tests for Unity on Android I'll see if we need to add something to guard against this.

**Comment by TobiasPott** [comment]
I close this issue as the FacebookUtil class no longer exists and login support using other auth methods is, afaik, not longer specifically implemented anymore.
If this issue arises with the latest version of the SDK and any third-party auth method feel free create a new ticket to discuss possible solutions.
