### ISSUE TITLE
Can't get installation to save CurrentInstallation data to local storage

### ISSUE THREAD

**Issue by AndrewLane** [parse-community/Parse-SDK-dotNET#248]
I'm seeing my installationId get persisted to local storage, but nothing else.  This means that when I relaunch my app, my ParseInstallation.CurrentInstallation object doesn't have all the installation data that I last saved.  It's basically a start-from-scratch object.  I'm stepping through the SDK code to figure out why, and here's the line I'm confused about:

https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParsePush/Public/ParseInstallation.cs#L245

I know that the CurrentInstallation won't get persisted unless the SetAsync method is called on line 248.  But the line on 245 prevents that in my case.  It seems to suggest that we don't need to call SetAsync if we're saving the current installation?  Maybe I'm misunderstanding that?  Please advise.

**Comment by AndrewLane** [comment]
ping

**Comment by edwardpotter** [comment]
No one wants to respond to this?  It's true - if you re-launch the app, the only value in ParseInstallation.CurrentUser is the InstallationId

I have found, however, that calling ParseInstallation.CurrentInstallation.SaveAsync() will repopulate some of the information.  After calling that on unity/ios I have information in AppName, DeviceType, LocaleIdentifier, InstallationId and AppVersion.  There is still no value in AppIdentifier or TimeZone, however.

**Comment by AndrewLane** [comment]
@edwardpotter as far as I know, this project is dead.  We ended up using the REST API to talk to Parse instead of this SDK.

**Comment by montymxb** [comment]
@edwardpotter unfortunately I cannot at the moment. I have no way of building the sdk to verify or test, for now at least.

@AndrewLane this project needs some TLC :/. The REST api is perfectly fine, but ideally this would be up to snuff to handle it without having to manage the requests. 

I'm interested in getting this up and moving again, but I have not had the capacity to do so lately. My windows dev computer crapped on me before I could get started on this, been just mac/linux lately.

It would be great if we had anyone else with a background in .NET who was interested in helping either rebuild/revitalize this (and has a working dev environment...), but for the moment there's been noone else who is actively maintaining this.

**Comment by edwardpotter** [comment]
@AndrewLane I'd think with something like Unity, going pure REST API would be pretty difficult.  With services like Buddy, back4app, etc. still being active and Unity being so prevalent - hard to imagine this SDK could be dead with those services basically depending on it for integration with Unity

**Comment by montymxb** [comment]
Marking this a potential issue we're going to look into. I'm thinking we're going to works towards having one or more tests that we can use to replicate this, fix it if we find a problem and guard against it in future releases.

**Comment by TobiasPott** [comment]
This issue should be solved with the newer version available in the master branch.
If any problems reoccur, feel free to create a new issue to discuss possible solutions.
