### ISSUE TITLE
Client loses connection after several scene loads in Unity.

### ISSUE THREAD

**Issue by WookieeJumper** [parse-community/Parse-SDK-dotNET#249]
I am working on a game in Unity that has a single hub scene which gets loaded after every mini game. The first time through everything works fine, but once the mini game is complete and I load back into the hub scene I can no longer communicate with the server. 

My ParseInitializer has DoNoDestroyOnLoad and I only ever have one in the game. Im at a loss as to what to do here.

**Comment by montymxb** [comment]
Can you please provide additional details as to the issue you're observing. Ideally this would be logs so we can help you pin things down. Closing this out in the meantime as this is nearly a year old... If you are still having an issue let us know and we'll open this back up.
