### ISSUE TITLE
Can not build with Visual Studio 2015 or the latest Xamarin Studio

### ISSUE THREAD

**Issue by Murf** [parse-community/Parse-SDK-dotNET#250]
Is anyone working on releasing 1.8.0 please?
or is there a workaround for the GCMSenderID problem with Xamarin Forms Android?

**Comment by montymxb** [comment]
We are currently working towards a 1.8.0 release. We apologize for the delay, it's been a while 😛 . I'm closing this out as it seems you're indicating #253 is a similar issue? If what you're experiencing is something different please provide additional details and we'll open this back up.
