### ISSUE TITLE
Task.Run incorrectly runs task on Synchronization.Current thread

### ISSUE THREAD

**Issue by benwulfe** [parse-community/Parse-SDK-dotNET#252]
See my PR here:

https://github.com/ParsePlatform/Parse-SDK-dotNET/pull/251

.net documentation explicitly states to use threadpool and mono does just that -- so I believe this is a bug in the parse library.  fix is in PR.

**Comment by montymxb** [comment]
Closed by patch in #251, thanks again @benwulfe !
