### ISSUE TITLE
How to use live query in Xamarin PCL

### ISSUE THREAD

**Issue by ra7bi** [parse-community/Parse-SDK-dotNET#255]
Hello all , im wondering to know how i can implement live update on my app , for example chat application without refreshing the page  i want to see any new messages .
i know there is a concept called live query but I'm not sure if it's supported for .net . 

please share your experience regarding this point . 

Thanks

**Comment by plyoung** [comment]
I think only the JS and iOS client SDKs support this atm. They seme to be working on Android support too. No idea what the plans are for .Net :(

**Comment by ra7bi** [comment]
any updates ?

**Comment by montymxb** [comment]
@ra7bi there is currently no live query implementation available for the .net sdk. As mentioned above it only a couple of the clients have implementations for live query interfacing. That being said it's not unlikely that we will bring this support into the this sdk at a future date.

**Comment by montymxb** [comment]
Closing in favor of the discussion in #199. Yes, we are planning on it. No, we don't have any ETAs yet.

**Comment by drinvojka** [comment]
sorry to reopen this .. Can we include parse live query in xamarin  ?
