### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/Parse-SDK-dotNET#257]
I have searched through the code how to add my serverURL but i have the impression that after Parse got deprecated this library has not been updated. In that sense, my question is if this project is still alive?

I am doing a small test on Unity but without being able to set my Parse Server's Url there's nothing I can do with the SDK

**Comment by plyoung** [comment]
I am guessing this..

```
ParseClient.Initialize(new ParseClient.Configuration()
{
	ApplicationId = "wotever",
	Server = "http://127.0.0.1:1337/parse/"
});
```

But I am not having any luck with the below code. The task just don't seem to ever complete.

```
public IEnumerator Test()
{
	Debug.Log("start");
	Task t = ParseCloud.CallFunctionAsync<IDictionary<string, object>>("hello", null);
	while (!t.IsCompleted) yield return null;
	Debug.Log("done");
}

public IEnumerator Register(string email, string pw)
{
	MainGUI.ShowMessage(Strings.Get(Strings._PlsWait));

	var user = new ParseUser()
	{
		Username = email,
		Password = pw,
		Email = email
	};

	Debug.Log("start");

	Task t = user.SignUpAsync();
	while (!t.IsCompleted) yield return null;

	Debug.Log("done");
}

```

**Comment by plyoung** [comment]
Made some progress. At least now I get a "NullReferenceException: Object reference not set to an instance of an object" when I try to make a ParseCloud.CallFunctionAsync call.

Check under Components > Scripts > Parse is ParseInitializeBehaviour. Dump that onto a GameObject and enter your app ID.

**Comment by jcguarinpenaranda** [comment]
Hello, do you have a working example ?

**Comment by montymxb** [comment]
@jcguarinpenaranda It lives! Going through issues atm, but expect a new release sometime later this month ;). Expect us to start small, we'll be focusing on core functionality first, native Windows implementations and such. From there we'll work on deving/testing for Xamarin, Unity, etc. Pace won't be fast but it will be moving.
