### ISSUE TITLE
Starter Projects need Updating

### ISSUE THREAD

**Issue by PunkStarStudios** [parse-community/Parse-SDK-dotNET#260]
The starter projects here are for the old Parse.com site. The code doesn't have anywhere to specify your own server address.

Can these be updated?

A simple matter that would have you scratching your head - but my problem is I can't get my dotnet clients to work (just REST and MacOS/iOS), so having a working starter project would go a long way to troubleshooting if the project is on my end or in the code base.

**Comment by plyoung** [comment]
Go through https://github.com/parse-community/Parse-SDK-dotNET/issues/166 and you find a build that includes it. It is in the sources but they never made an official build.

This project feels so dead :(

**Comment by PunkStarStudios** [comment]
Hey - thanks for the note.
I went through that thread you noted.
The only link I found that went to code that had sample projects... was the existing sample projects found already (based on parse.com with no server setting).

But maybe I missed it.

Can you pull out the link for me?
Pretty please? ;P

**Comment by plyoung** [comment]
This one https://github.com/parse-community/Parse-SDK-dotNET/issues/166#issuecomment-193965729
or this https://github.com/parse-community/Parse-SDK-dotNET/issues/166#issuecomment-194141770
includes the Parse.Unity.dll (cant remember which I use)

**Comment by vladrad** [comment]
Hi I just added added instructions in #166 on how to build.

**Comment by PunkStarStudios** [comment]
p@plyoung - nope. No sample projects in either link.
Thanks anyhow.

Same issue remains... if someone can post a working Parse .net project with a server setting in the configuration - that would be dandy.

**Comment by plyoung** [comment]
@PunkStarStudios As I stated before. This comment includes a link to the Parse.Unity.dll https://github.com/parse-community/Parse-SDK-dotNET/issues/166#issuecomment-194141770 He gives a link at the bottom of his message.

I am using it now and it works. 

Here is a direct link to the file provided https://github.com/ParsePlatform/Parse-SDK-dotNET/files/164631/Parse.Unity.zip

**Comment by PunkStarStudios** [comment]
Maybe I am missing something... or I am being unclear or simply an idiot...
But I am not looking for a DLL (I am not using unity)... I am looking for a startup project for either C# or VB.net... be it for VS2015 or whatever.

That link above - has 2 files - a DLL and an XML. No idea what the XML is all about - looks to be some spec file to go along with the DLL... probably enumerating the DLL hooks for a Unity project it gets dumped into or something.

So tell me - am I missing something? Where's the SLN files or whatnot?

**Comment by plyoung** [comment]
Sorry, I was under the impression you are talking about the Unity version sine it is also hosted in this repo. The DLL I linked will not work for you.

**Comment by PunkStarStudios** [comment]
WHEW! I thought I was missing something.
 - oh and I looked at the repo - that's the problem (hence my original post)...

The starter projects in the original repo don't work - they are based on the old parse.com server implementation and not a self hosted one with a server link pointing elsewhere.

**Comment by vladrad** [comment]
@PunkStarStudios Try looking at the bottom of #166 and see if you can build the dll's like that (select all the project builds that are not unity). Then import them to a new project and see if you can init the library.

**Comment by plyoung** [comment]
You will have to build it. The Server option is available in the source. From Unity sources for example this call can be done; which should be the same for non-Unity app. 

```
ParseClient.Initialize(new ParseClient.Configuration {
  ApplicationId = applicationID,
  WindowsKey = dotnetKey,
  Server = string.IsNullOrEmpty(server) ? null : server
});
```

**Comment by PunkStarStudios** [comment]
Well then - I am at a loss....

I've tried those that to no avail. I simply can't get a .NET client to either authenticate a user or simply pull back data.

https://github.com/parse-community/parse-server/issues/3674
https://github.com/parse-community/Parse-SDK-dotNET/issues/259

Everything works fine via REST or MacOS/iOS... but nothing but invalid server responses when attaching via the .NET Parse framework.

That's why I was trying to get sample code.
But your latest reply not withstanding, the repo should get updated sample projects to reflect the current environment for "newbies".

**Comment by vladrad** [comment]
@PunkStarStudios do you happen to have an error you are getting from parse? Have you tried sniffing the traffic to see what the generated curl looks like?

https://www.charlesproxy.com/

I highly recommend charles. Once you install the certificate you will be able to add your server to a list to sniff the traffic. You will be able to sniff and get the curl for the login call, then you can look at it and compare it to the one your are doing.

**Comment by PunkStarStudios** [comment]
Holy hell - THANK YOU @plyoung 

That server assignment code did the trick.
using "Server = "https://myserver.com/myapp/" wasn't working.
But your
Server = string.IsNullOrEmpty(server) ? null : server
DOES!
YAY!
