### ISSUE TITLE
invalid signed request

### ISSUE THREAD

**Issue by okarpov** [parse-community/Parse-SDK-dotNET#261]
Hello,

When I change AppID and Secret from previous fb account to AppID and Secret of another facebook account app it gives me "invalid signed request" error.

What the problem in? Any idea please.

**Comment by vladrad** [comment]
@okarpov can you give a little bit more info?

How are you hosting this? do you have any logs?

**Comment by okarpov** [comment]
@vladrad Hello, 
nothing special, just simple ASP.NET MVC website hosted on IIS.
Here is the exact stack for the exception:

the following error:
System.InvalidOperationException: Invalid signed_request
   at Facebook.FacebookClient.ParseSignedRequest(String appSecret, String signedRequestValue)
   at Microsoft.AspNet.Facebook.Client.FacebookRequestHelpers.GetSignedRequest(HttpContextBase context, Func`2 parseSignedRequest)
   at Microsoft.AspNet.Facebook.FacebookAuthenticationModule

So, if I put ID and Secret back to the previous account - it works fine, changing it to a new AppID and Secret gives the exception when my facebook app is just opened under facebook iframe

I did try to clear all local storages but it didnt help

Any idea?

**Comment by vladrad** [comment]
@okarpov Im a little confused as I cannot find any facebook code in the Parse project...

**Comment by okarpov** [comment]
hmm, why facebook url leads to this github repo? strange

**Comment by vladrad** [comment]
I have no clue, but there is no facebook code int he parse project. Not that I can see.

**Comment by okarpov** [comment]
ok, thx and sorry
