### ISSUE TITLE
ASP.Net Development

### ISSUE THREAD

**Issue by PunkStarStudios** [parse-community/Parse-SDK-dotNET#262]
Hopefully I don't get slapped for this...
But does anyone have a sample web project using the .NET SDK? Be it C# or VB? MVC or forms even?

The learning curve for me transitioning from Objective-C and VB6 to an ASP.NET development is a tiny bit steeper than I anticipated - the syntax for passing ParseObjects around in a MVC environment is ... well... probably simple to most but a bit of a mystery to folks like me. ;P

**Comment by ombinar** [comment]
Refer to this guide for any .NET development.
http://docs.parseplatform.org/dotnet/guide/

Here you can download starter projects for mobile but should be similar to other applications:
https://github.com/parse-community/Parse-SDK-dotNET/releases/tag/1.7.0

**Comment by PunkStarStudios** [comment]
Sorry - that's not helpful at all.
async with web forms and MVC seems to be pretty tricky.
That along with the built in authentication that is included with the templates is making it less straightforward.

The link you provided - has practically no code - nothing ASP related - and not even for parse server (they are for the old parse.com).

**Comment by ombinar** [comment]
You right, it's not straight forward and lots of learning curve. I would suggest Google "parse .net mvc async" and you will see lots of snippets.

but here's a MVC snippet that is an async (go to the suggested answer):
http://stackoverflow.com/questions/27408452/awaiting-query-findasync-from-parse-doesnt-work

**Comment by montymxb** [comment]
Unfortunately we don't have any examples at this time for you. If you looking for help getting started I would recommend you search for or drop some questions over at stackoverflow and see if you can find some reliable resources to start with.
