### ISSUE TITLE
[Unity3D] Parse 1.7.0 & Firebase conflict while building 64-bit iOS

### ISSUE THREAD

**Issue by artourky** [parse-community/Parse-SDK-dotNET#264]
We are using Unity 5.5 and Parse 1.7.0 which doesn't have "Parse.Unity.dll" and while on Editor everything is working fine but when we build using il2cpp on iOS the game produces an error of "MissingMethodException:  No constructor found for Parse.Common.Internal.FlexibleListWrapper`2".

I think it's because of stripping, I've tried to include "Parse.Core" and "Parse.Common" in "_link.xml_" but still same error while I was looking for solutions I found that there's a file "Parse.Unity.dll" that should have been in the project from the start but when I try to include it in our project another error but this time in Unity Editor that says "System.Threading.Tasks.Task is defined multiple times" and that's because -I think- *the new* Parse.Unity.dll and Unity.Task.dll from Firebase, if I try to delete that firebase Dll another error appears....

Please any help is appreciated :(

**Comment by subhradeepc** [comment]
Even im stuck with the "System.Threading.Tasks.Task is defined multiple times", any help ? guys ?

**Comment by montymxb** [comment]
Closing as it looks like this should be fixed by #267. A release is not yet available for this. I'm going through a bunch of the existing issues first to see the state of things, so stay posted.
