### ISSUE TITLE
Release 1.7.0 doesn't work in Unity with custom server

### ISSUE THREAD

**Issue by CapeGuy-Ben** [parse-community/Parse-SDK-dotNET#265]
This is because the `ParseInitializeBehaviour` is required to be instantiated in the [Unity](https://unity3d.com/) SDK to setup the async-task processing (otherwise async Parse calls never complete) but it doesn't allow you to pass a custom server URL for it to use in the `ParseClient.Initialize()` call it makes.

**Fix:** I've created a fork and added a [1.7.1 release](https://github.com/CapeGuy-Ben/Parse-SDK-dotNET/releases) with (just) a fix for this issue [here](https://github.com/CapeGuy-Ben/Parse-SDK-dotNET).

**Note:** This issue also seems to be fixed in the latest code in the master branch but I wasn't sure how to use that against my pre-existing project.

**Comment by CapeGuy-Ben** [comment]
Actually, after some more testing, there's also an issue with the `ParseInitializeBehaviour.OnApplicationPause()` method not initializing the ParseClient properly. I will recreate the release on [my fork](https://github.com/CapeGuy-Ben/Parse-SDK-dotNET) with that fixed too.

**Comment by CapeGuy-Ben** [comment]
That's fixed now and I've recreated the 1.7.1 release on that fork. I wasn't sure how the sample projects are generated so I left that zip out from the release rather than adding a broken version.

**Comment by montymxb** [comment]
Hey @CapeGuy-Ben I'll see if I can't take a look at this during this upcoming weekend. If you've managed to put together a fix would you mind putting up a PR for it here? From there we can take a look at it and see how it works out 👍 .

The goal here is to get the **.NET**, **Arduino** and **Embedded C** sdks up to snuff with parse-server. I'll be moving this along to see if we can't get that achieved in a decent time frame. From what I've heard though the **.NET** is good to go as is. Just missing some of the newer functionality that's been added.

**Comment by CapeGuy-Ben** [comment]
Hey @montymxb! I did try to put a pull request in but as there's no branch for release 1.7.0 I couldn't work out how to do it. My fix is a minor edit to version 1.7.0 rather than an edit to the (now significantly different) master branch.

**Comment by montymxb** [comment]
The releases are generated off a given commit from a given branch, specified by a user. It's very akin to [git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging). Github just makes it convenient and automatically generates the zips and tars as well.

As for creating pull requests from a fork, there's info on how to do that [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). Although the current master be a bit ahead of where you forked, it looks like the change you made was just a one liner? You could even just go to the file [directly](https://github.com/parse-community/Parse-SDK-dotNET/blob/master/ParseCore/Public/Unity/ParseInitializeBehaviour.cs) and chose to Fork and Edit just that file from the browser (it's the little pencil icon on the top right) considering that it's a pretty small change.

**Comment by CapeGuy-Ben** [comment]
This change is already in the master branch, but the master branch also contains API changes which make it incompatible with the pre-existing Parse project which I'm trying to move over to a custom server. So I made this simple single commit change against 1.7.0 which fixes using it with custom servers in Unity. Think of it as a hot-fix for 1.7.0 rather than a new release. If you're planning on releasing a new version against master anytime soon then just ignore this. There are quite a few people struggling with this issue though. See [this issue](https://github.com/parse-community/Parse-SDK-dotNET/issues/166).

FYI. I know what a release is (I did one on this fork) and I know how to create a pull request in GitHub, however, it needs to be a pull request *against a branch in the target repo* and there is no branch sitting where the 1.7.0 tag is in your repo so I can't do a pull request unless you create one.

**Comment by montymxb** [comment]
@CapeGuy-Ben The intent here will be to push out a new release, eventually. If a fix has already been integrated into the master for this then it seems I misunderstood... Once the next release is published we should be ok.

I did take a look at the aforementioned issue as well. I see what you're getting at regarding the custom servers. Since I'm just stepping on this I'll be verifying the existing tests and such for starters, then going through the rest of these issues and resolving what we can 👍 . From there we'll be pushing out a new release altogether.

You'll have to forgive me for that, don't take the excessive detailing personally. It appears I glazed over the fact you were suggesting a merge onto a branch poised at release `1.7.0` itself, oops! We won't be going that route however, given that the focus is to push up a new release altogether.

With all that, you mentioned that the `master` contains breaking changes? That's no good :/ .... I've only recently been looking into this so I'll have to see exactly what was done, unless you know of any particular examples you could bring up. I'll be checking tests and such this weekend.

If there's anything else you think would be prudent to mention please do! The faster I'm able to catch up with the current state of affairs the sooner we can move onto the fixing 🔧.

**Comment by CapeGuy-Ben** [comment]
Hey @mintymxb, sounds good. Don't worry, nothing taken personally - just trying to do a better job of explaining the situation! Good luck putting together a new release. 👍

A few things that might be worth thinking about:
- I tried building the project (1.7.0 and master) on my Mac via Xamarin Studio and then on my PC via Visual Studio 2017 & 2015 Community editions and couldn't get them to build without lots of errors about unsupported project types. I was only able to build everything once I tried Visual Studio Enterprise 2015 which prompted me to install all sorts of extra bits and bobs to get the remaining projects working. It might be worth working out what the dependencies of the project are and listing them in the readme so people without Visual Studio Enterprise can also build it?

These issues were from trying to build the master branch, it was about a week ago so some of details are a little hazy :-/. It's also quite possible that the second of these issues was caused by me grabbing the wrong dlls while trying to fix the first issue:
- After building master the instructions to find the build results in the `Parse/Bin` folder are no longer correct, I had to go rooting around the various build folders to find what I *thought* were the right dlls.
- Once I swapped in the build from the master branch (I tried that before deciding a slightly modified 1.7.0 was the way to go) I got a few compile errors in my pre-existing Unity project. Presumably that is because there are missing/changed bits of the API. I can't remember exactly what they were off the top of my head but I can take another look and let you know if that would be helpful?

**Comment by montymxb** [comment]
Thanks! Yeah it's going to be interesting, especially considering that the CI configuration appears to have been server-side at appvoyer, and that's gone now :/.

I can confirm the issues with VS 2017, looking into this a bit (and a helpful [so post](https://stackoverflow.com/questions/43012179/cant-add-silverlight-8-support-in-visual-studio-2017)) it appears VS 2017 does _not_ support silverlight projects, or 8.0/1. Although these work in VS 2015 (with the necessary dependencies for xamarin and such), there's no guarantee that these will ever be accessible in VS 2017. I need to do more research before I proceed but that's certainly a problem if you're on 2017.

I haven't looked into the building issues yet, but perhaps there's something up there as well. Looking at #91 it looks like they were in the middle or porting everything over to UWP. Once I've setup my dev environment properly for this I'll see where things are.

I'll be around working on this from time to time in the near future. If you think you've found anything else that's of significance feel free to bring it up. It'll take a while to really look through most of the issues to check for any reported compatibility problems, but after that we should start getting some PRs rolling in! Once things are stable (and the CI is back in place) we'll have ourselves a release 👍 .

**Comment by CapeGuy-Ben** [comment]
Thanks for looking into it. I will let you know if I find anything else. I'm going to close this issue as anyone using Unity can use the 1.7.1 release on my fork until another release comes along and once there's a new release they can use that.

BTW. I think the users would be happy to install VS 2015 Community for building the project. Just add the requirement to the ReadMe file.

**Comment by montymxb** [comment]
@CapeGuy-Ben No problem. Hopefully we can get this project back on it's feet!

**Comment by cabhara** [comment]
@richardjrossiii or anybody: Is there a release that has the fix for the Android Push Notification Registration error? `Found com.parse.push.gcm_sender_id <meta-data> element with value "id:190765109935", but the value is missing the expected "id:" prefix.`
We were not able to create a working dll from the master, so I'm looking if anybody has compiled a Parse.Unity.dll that contains this bug fix.

**Comment by montymxb** [comment]
@cabhara not that I am aware of. If this is still outstanding can you open up another issue specifically for your problem?
