### ISSUE TITLE
How can I implement one user get one record?

### ISSUE THREAD

**Issue by truonguit2010** [parse-community/Parse-SDK-dotNET#270]
Hello,

I want to build a system like:
1. one user can ask many questions.
2. one answer can get only one question, and other users cannot have this question.

How can I implement it with parse object? Please point me a start point. 

Thank you.

**Comment by montymxb** [comment]
Please check out the docs section regarding [relational data](http://docs.parseplatform.org/dotnet/guide/#relational-data) for seeing how you would go about this.
