### ISSUE TITLE
Unity: how to get Android notifications working?

### ISSUE THREAD

**Issue by cabhara** [parse-community/Parse-SDK-dotNET#271]
I followed the Unity Parse Push example (using Parse 1.7.0 parse dll). Pushes are working fine for iOS, but getting problems for Android as things have changed with Firebase etc. since the example was done. Is there a newer example or tutorial for getting Unity Android pushes to work? Especially I'm trying to find out how to set the GCM Sender ID in Unity. (Using back4apps as the server) All documentation I can find is for pure Android, not for Unity.

**Comment by montymxb** [comment]
Could you provide further details in regards to this issue? Logs and such?
