### ISSUE TITLE
Compiled DLL for Unity 2017.1.1f1

### ISSUE THREAD

**Issue by ColossalChris** [parse-community/Parse-SDK-dotNET#272]
I had this successfully working well with the prev 2017 version of Unity, but since updating I am now getting errors when trying to build for some platforms. Does anyone have the dll's compiled for the newest version of Unity?

**Comment by montymxb** [comment]
@ColossalChris could you provide some of those errors during compilation?

**Comment by TobiasPott** [comment]
As we now have a support for non standard .NET platforms with @TheFanatr pull request, I'll close this issue in favor of any new issue which may arise from the current state of the repository and newer versions of Unity.
