### ISSUE TITLE
Unable to initialize Parse

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/Parse-SDK-dotNET#282]
I am just starting with Parse and Unity, and I'm not able to initialize Parse. 

I'm getting the following error:

![captura de pantalla 2017-12-19 a las 8 00 42 p m](https://user-images.githubusercontent.com/7200821/34186052-6181f5de-e4f7-11e7-8b44-c47c4b4f9467.png)

I have a blank project, with the files: 

![captura de pantalla 2017-12-19 a las 8 00 50 p m](https://user-images.githubusercontent.com/7200821/34186061-7121d428-e4f7-11e7-9bd0-fbba1d1e9633.png)

Where `ParseInit.cs` is the script on which I am initializing Parse. 

And here's the code for that file:

![captura de pantalla 2017-12-19 a las 7 59 47 p m](https://user-images.githubusercontent.com/7200821/34186080-9b778894-e4f7-11e7-8056-560dcd5c8b61.png)

As you see, right now I am only logging to the debug console the ParseClient class, but I'm getting the error I mentioned above, which says that ParseClient is defined multiple times.

Do you know how it can be solved? Or why is this error showing up?

Thank you

## Edit

My environment is MacOSX El Capitan, and my version of Unity is the `2017.1.0f3 Personal`

**Comment by jcguarinpenaranda** [comment]
## Fix

I had copied all the `Parse-1.7.0` folder. To fix this, I replaced the whole folder with one of its subfolders.

Instead of importing `Parse-1.7.0` I imported the `Parse.Unity` folder that was inside.

## New problem

Now, after having imported the right folder, I have this very simple script copied from the docs:

![captura de pantalla 2017-12-19 a las 9 11 18 p m](https://user-images.githubusercontent.com/7200821/34187817-39450034-e501-11e7-8215-c86101db314a.png)

After running it, I understand it should save an object to my database. Instead nothing happens.

Also, If I try to place the lines 20-23 in a separate file, I get an `AggregateException`

![captura de pantalla 2017-12-19 a las 9 13 50 p m](https://user-images.githubusercontent.com/7200821/34187882-8f3c5776-e501-11e7-917b-d851cd767939.png)

**Comment by jcguarinpenaranda** [comment]
I think this set of questions and answers may be valuable for other people that are starting with this SDK like me.

## Fix 2

To fix the previous error, I had to go in Unity to **Edit > Project Settings > Script Execution Order** and set `ParseInit.ts` (The file where I initialize the Parse SDK) as the first script. Then `ParseTest.ts` as the second script, like this:

![captura de pantalla 2017-12-19 a las 9 52 31 p m](https://user-images.githubusercontent.com/7200821/34188932-f1dce4cc-e506-11e7-90ee-3b33047aa939.png)

## New Problem

Now that the `AggregateException` is not being thrown anymore, I still can't get the SDK to connect to my server, which is running in the localhost.

I tried adding and removing a `/` at the end of the Server string but nothing seems to work. I wrote the following script.

![captura de pantalla 2017-12-19 a las 9 48 48 p m](https://user-images.githubusercontent.com/7200821/34188996-53d1ad5c-e507-11e7-96e0-dcf9d0aed11c.png)

No Exceptions are thrown, and nothing is being logged to the console.

**Comment by montymxb** [comment]
We don't currently have active tests running against unity at this time. As such I'll have to take a look at this personally and let you know if there's something up.

**Comment by jcguarinpenaranda** [comment]
Thank you, please any help will be very appreciated


2017-12-20 18:50 GMT-05:00 Benjamin Wilson Friedman <
notifications@github.com>:

**Comment by jcguarinpenaranda** [comment]
Excuse me, I want to be proactive searching for a solution. What should I do? Is there anything I have to check again?, or maybe give you more details?

**Comment by montymxb** [comment]
@jcguarinpenaranda sorry to the lack of feedback. I have been working on putting together a method for building the current sdk, as it has differed significantly from the original instructions provided. 

I've managed to get the basic components built for .NET, but I haven't started testing/building against Unity yet. That's the next thing in addition to Xamarin.

**Comment by jcguarinpenaranda** [comment]
Thank you so much, I will be waiting and if there's anything you need me to do in order to test this with Unity just tell me

**Comment by roddrift** [comment]
How does this even work? I cloned the git and put it in the assets folder and it is a mess - msbuild / xbuild produces nothing but errors - is parse a lost cause on Unity?

**Comment by montymxb** [comment]
@roddrift building with xbuild/msbuild on mac is currently non-functional. The same Dlls can be produced by building on windows, which I would recommend until that is resolved. 

We're in the midst of some changes coming up for the sdk with potential support from additional contributors, from there we'll get some new Dlls, but serious Unity support may be coming later on. You can follow the discussion over in #274.

**Comment by roddrift** [comment]
Thanks @montymxb, appreciate the response.

**Comment by jcguarinpenaranda** [comment]
Hello, I just wanted to return to this issue as I have not been able to test with Unity again. Is there anything I can do to help? or, is everything working ok now?

**Comment by ycy1164656** [comment]
HI! Have you solved your problem? because now I have quite the same problem as yours. I can initialize parse, but I can't reach the server.The error message is "OtherCause" . So I can not know which step of initialize is wrong.

**Comment by jcguarinpenaranda** [comment]
Hello, has someone been able to solve this?

**Comment by TobiasPott** [comment]
@ycy1164656 @jcguarinpenaranda I assume you are using the parse version prior to the "Update Project" commit from alex on [Dec. 22 2018](https://github.com/parse-community/Parse-SDK-dotNET/commit/d0577f4d0979ddadce0c535146a572c3ca31fed0)?

I'm not sure if any changes regarding your issues were made before that commit but for now there is no direct support for Unity as a platform for the current state of the repository.

If it is very urgent I can check for my branch for Unity support on my fork of this repository.
But that one is neither official nor tested beyond my own needs and will require Unity 2017 or newer.
Let me know if that would be an option for you and I'll check which of my branches is the compatible and update it to the latest commit of the official repository.

**Comment by Fangh** [comment]
0. I use Unity 2018.3.0f1
1. I built the current master branch with Visual Studio 2017
2. I copy the "netstandard2.0" folder in my /assets folder
3. I Added the link.xml as written here : http://docs.parseplatform.org/unity/guide/#getting-started
4. I created a very simple script :

![image](https://user-images.githubusercontent.com/6020679/54870525-f1049f80-4da7-11e9-8a9f-283d590a69c3.png)

5. this is the error I get in my console : 

![image](https://user-images.githubusercontent.com/6020679/54870531-02e64280-4da8-11e9-87f6-b433a7199106.png)

**Comment by TobiasPott** [comment]
@Fangh 
Oh, I've never noticed the link.xml hint in the getting started until now.
As I understand it's content it's used for the notification feature of Parse, unfortunately it refers to the old version of the Parse SDK for .NET and since the last repository update from alex @TheFanatr there is no built-in support for Unity at all and some parts of the .NET standard implementation do not work because of the way Unity compiles your code into assemblies and which one becomes the entry assembly of your application.

The code you are getting the exception from is affected by this. You may check out my working branch for Unity support which covers this issue and handles wrapping Unity version stuff for the access in parse. https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/recode-unity-support 
Hint: It changes some other portions of the code to make it compatible with .NET standard applications and Unity applications and is not an official repository. It also does not yet include the notification feature. If  you require the notification feature, I think you are stuck with an older version of the SDK unfortunately.

As alex stated in another thread, unity support is removed and will be brought back when a plugin structure, but I can not tell you when that will be ready.

If you try my current branch for unity support I'll please refer to any issues you have with a new thread on that repository instead. I'm happy to help and improve it aside from my own requirements.

**Comment by Fangh** [comment]
Thanks a lot for having taking time to show me a Unity version of the SDK you created. It will be so helpful for everyone. Maybe the admin of this repo should link your project in the readme so everyone using unity could use your SDK !

**Comment by TobiasPott** [comment]
I close this issue as most problems discussed here were either solved with the latest version available from the master branch or in the past by forked repositories.
The latest version works with Unity on iOS and Android and several other target platforms, which may require additional configuration of the SDK using the mutators @TheFanatr has introduces with his pull request. Please take a look on the [use-in-unity-client](https://github.com/parse-community/Parse-SDK-dotNET#use-in-unity-client) section of the readme.
