### ISSUE TITLE
Unity API errors when Task.ContinueWith() callbacks exceed depth of 10

### ISSUE THREAD

**Issue by zvinless** [parse-community/Parse-SDK-dotNET#283]
Because `ContinueWith()` callbacks seem to get executed on the calling thread for the first 10 levels, I expect the same for callbacks of any depth level. Found on Unity 2017.2.1, macOS 10.13 in the Unity Editor.

Seems to be related to changes made in 1c59dbfa84c84fddc6e9ffd6718d4076c6e4f10a

When a task's callback depth exceeds 10, a `TaskFactory` is now new'd with the default synchronization context as opposed to Unity's `UnitySynchronizationContext` (`SynchronizationContext.Current`), which causes the `ContinueWith` callback to potentially run outside of the main thread. This can lead to issues with the Unity API.
See:
https://github.com/parse-community/Parse-SDK-dotNET/blob/ce87d7f392423d40459149ee5e4d71d4edfd5bdf/Unity.Tasks/Public/Task.cs#L22-L25

Here is an example MonoBehaviour that will result in an error (there are no errors when using the `TaskFactory` class prior to 1c59dbfa84c84fddc6e9ffd6718d4076c6e4f10a, and also no errors at lower depth values):
```csharp
using System.Threading.Tasks;
using UnityEngine;

public class UnityTaskError : MonoBehaviour
{
	TaskCompletionSource<float> tcs;

	void Start()
	{
		tcs = new TaskCompletionSource<float>();

		var task = tcs.Task;
		for (int i = 0; i < 11; ++i)
		{
			task = task.ContinueWith(_ => Time.time);
		}

		Invoke("CompleteTask", 1);
	}

	void CompleteTask()
	{
		tcs.SetResult(0);
	}
}
```

> get_time can only be called from the main thread.
> Constructors and field initializers will be executed from the loading thread when loading a scene.
> Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

**Comment by montymxb** [comment]
Hmmm, this might be related to [this](comment) regarding that feature coming in. So I'm gathering that you've built up this SDK against the latest code available and you got this? If so we may just want to revert this change...

**Comment by zvinless** [comment]
Yeah, although I haven't seen anything in the SDK that actually gets 10 levels deep. I was just trying to use the Task shims for other stuff in a project and saw that this was an issue. Maybe @benwulfe has some insight since it seems that the change was intended to resolve another issue?

**Comment by TobiasPott** [comment]
This issue hasn't seen any activity for quite some while and support for async-await in Unity has improved over the past years.
I close this issue and invite you to check the latest SDK version for this issue and create a new ticket if you encounter any problems.
