### ISSUE TITLE
Unity 2017.1 InvalidOperationException: Header value contains invalid characters

### ISSUE THREAD

**Issue by fsufyan** [parse-community/Parse-SDK-dotNET#286]
Hi,

I am getting this error when initializing parse Unity SDK 1.7.0 although the same project was working fine in Unity 5.6 before upgrading to Unity 2017.1.0 and 2017.1.1
Is this plugin not supported on Unity 2017 ?

**Console Log:**
InvalidOperationException: Header value contains invalid characters
UnityEngine.Networking.UnityWebRequest.SetRequestHeader (System.String name, System.String value) (at C:/buildslave/unity/build/artifacts/generated/common/modules/UnityWebRequest/WebRequestBindings.gen.cs:479)
UnityEngine.WWW..ctor (System.String url, System.Byte[] postData, System.Collections.Generic.Dictionary`2 headers) (at C:/buildslave/unity/build/Runtime/WebRequestWWW/UWRWWW.cs:62)
Parse.Internal.HttpClient.GenerateWWWInstance (System.String uri, System.Byte[] bytes, System.Collections.Hashtable headerTable)
Parse.Internal.HttpClient+<>c__DisplayClass0_3.<ExecuteAsync>b__5 ()
Parse.PlatformHooks+<RunDispatcher>d__51.MoveNext ()
UnityEngine.Debug:LogException(Exception)
Parse.<RunDispatcher>d__51:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by fayyadsufyan** [comment]
I am not using the modularized version since it lacks the ParseFacebookUtils and i am in need of it.
I was trying to upgrade my project from 5.6 to 2017 for performance comparisons but i think i will wait for an official new Parse Unity sdk update.

**Comment by montymxb** [comment]
@fayyadsufyan we've been hearing that there's been issues using the old sdk with the latest unity (and sometimes the old unity as well). The new design should eventually reincorporate unity integration, but for now there's not really anything here that will work the latest Unity builds, sorry. Hopefully we'll get this back in place sometime soon.

**Comment by TheFanatr** [comment]
@montymxb The master branch should work with Unity, as long as you have the Unity 2018.1.0b9, and you adjust your player settings to reflect the configration below.

Scripting Runtime Version: "Stabe (.NET 4.x Equivalent)"
Api Compatibility Level: ".NET Standard 2.0"

Please note that you have to set them in that order, otherwise .NET Standard 2.0 compatibility will not be shown.

**Comment by montymxb** [comment]
Ahh, I stand corrected!

It just occurred to me we need to start updating the README for the new sdk's requirements. These can be _rough_ until we know exactly what we need to set things up, and with instructions per platform most likely. Those settings mentioned above would be excellent to add to that.

**Comment by TobiasPott** [comment]
As mentioned by @TheFanatr previously the support for .NET 4.5 or .NET Standard is available on any platform now which supports it (e.g. Unity 2018.1.x or newer).
