### ISSUE TITLE
Transfer of NuGet Package Ownership

### ISSUE THREAD

**Issue by montymxb** [parse-community/Parse-SDK-dotNET#287]
As requested by NuGet support I am opening up an issue regarding transfer of control for the Parse NuGet package. When the community org was created we did not properly receive access for this. This issue is part of a formal process for us to get ownership back. I will be taking ownership of it myself initially. The intention is to then give the current team members access.

It has been requested this remain open for at least 24 hours so anyone can comment. If there's no problems with this request it has been noted that someone else with proper privileges should close this issue (besides myself). 

@flovilmart if you can close this out around 6pm tomorrow that would fantastic. Expecting that we should be able to move along with regaining control after that. I'll probably ping you as well just in case.

**Comment by montymxb** [comment]
@parse-community/core-maintainers it has been over 24 hours. If anyone (besides me) can close this at their convenience, as noted in the description for the issue above, that would be super. Once that's done we can get this moving along 👍 .

**Comment by flovilmart** [comment]
Doesn’t seem that anyone oposes the transfer!

**Comment by montymxb** [comment]
@parse-community/core-maintainers letting everyone know that we completed the transfer and we have control of the account again. Still need to grant access to other team accounts, but we're looking good now.

**Comment by flovilmart** [comment]
What a way to end the week! Awesome!
