### ISSUE TITLE
ParseUser.CurrentUser.FetchAsync() not working

### ISSUE THREAD

**Issue by BrixtonDynamics** [parse-community/Parse-SDK-dotNET#289]
I've inherited a project that uses Parse.unity. The user data syncs on some devices but not others. 

if (ParseUser.CurrentUser != null)
		{
			// always gets here
			ParseUser.CurrentUser.FetchAsync().ContinueWith(s =>
		      {
                          // does NOT get here on some devices
		       });

On some devices (can't say which ones, happens on both iOS and Android devices) the code never gets the data from the server. 
I don't know how to diagnose this problem because this code works on most devices, and there is no error message. 
Once a device is unable to fetch from the server, it stays like this. Uninstalling and reinstalling, deleting cached data doesn't help. 

What could be the problem here? How can I begin to diagnose this?

TIA,
Tai

**Comment by TobiasPott** [comment]
@BrixtonDynamics I close this issue for now as I've not experienced any similar issue for the last two years now and the new version of the SDK is available from the master branch now.
If this is still an issue on your side, i would ask you to check whether it still exists using the version 2.0 of Parse SDK and provide additional information and create a new issue to discuss possible solutions.
