### ISSUE TITLE
Updated version on NuGet.org?

### ISSUE THREAD

**Issue by Spiralis** [parse-community/Parse-SDK-dotNET#291]
Version 1.7.0 does not work for me (failing on init). Master (version 2.0.0) however does (even if the server is not 2.0.0). 

But, the problem is that version 2.0.0 of the parse sdk is not available on NuGet, so our build-server fails. I see from older discussions that 1.8.0 was a planned release. I haven't tried that branch though.

Are there any plans for updating NuGet.org with a newer version?

**Comment by TheFanatr** [comment]
Once the unit tests for the master branch have been written, automatic NuGet publishing can be set up by reconfiguring the AppVeyor build settings. As of right now, you can generate a NuGet package by building from source, but you can also just reference the .dll file that is also generated. If you cannot figure out how to generate a NuGet package, [here is a link to the one generated by the AppVeyor build from the latest commit](https://ci.appveyor.com/api/buildjobs/n1dmjiilqfn9e0g0/artifacts/Parse%2Fbin%2FDebug%2FParse.2.0.0.nupkg).

**Comment by TheFanatr** [comment]
As for "version 1.8.0" that is in it's own branch, it is an unfinished older version of the project kept as a backup, in case the master branch has some kind of major issue. It is also useful as a reference source when making modifications to the master branch.

**Comment by Spiralis** [comment]
Ok. I added it as a binary dependency already. Thanks.
