### ISSUE TITLE
Xamarin Mac Parse Issue...

### ISSUE THREAD

**Issue by johng1492** [parse-community/Parse-SDK-dotNET#296]
Is anyone using ParseClient on Xamarin/VS for Mac? I have tried and tried and tried to either use the Parse 1.7/Parse.Android 1.7 or Parse.NETStandard2 to be able to hit my Parse server and NOTHING has worked at all. I've searched online and followed countless suggestions with no success at all. I have run the libraries in the native project as well as in the FORMS project, and nothing. Suggestions anyone? 

When I run Parse.NETStandard2, I get an NOENTRYPOINTFOUND: GetModuleFileName exception. Oddly, when I use the method, I see that a request gets sent to the Parse server, but doesn't save data, only sends a request.

When I run the 1.7 libraries, I don't get an exception but it will not save or query data from the backend at all. Oddly, when I use the method, I DO NOT see that a request gets sent to the Parse server and doesn't save data at all.

PLEASE HELP!!

**Comment by flovilmart** [comment]
Can you share a demo project?

**Comment by johng1492** [comment]
The issue is upgrading Xamarin/VS Mac to .Net Framework 4.6.1. My select framework is 2.0 and I have a sample console app that I downloaded that references 4.6.1. I can't figure out how to upgrade my framework. Thoughts?

**Comment by flovilmart** [comment]
Can you please share a demo project? Or explain why you can’t share one.

**Comment by johng1492** [comment]
flovilmart, 

Thx for the response. Oddly, I began a project from scratch on Xamarin.Forms Mac and, using Parse.Android as a reference, I was able to save my data to the backend server. So weird. Anyway, thanks again.

**Comment by flovilmart** [comment]
So this issue can be closed?
