### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by TobiasPott** [parse-community/Parse-SDK-dotNET#299]
Hi! I'm trying to build the project using Visual Studio, but I'm getting these errors while trying to open it.

C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse\Parse.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse\Parse.csproj

C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse.Test\Parse.Test.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse.Test\Parse.Test.csproj

_Originally posted by @WalGallen-Baktun in https://github.com/parse-community/Parse-SDK-dotNET/issues/294#issuecomment-441079930_

EDIT: moved to a new issue as it is not directly related to the original topic

**Comment by TheFanatr** [comment]
@WalGallen-Baktun I will be closing this issue now. If needed, you can request for it to be reopened for you.
