### ISSUE TITLE
UWP local file access issue

### ISSUE THREAD

**Issue by stephenhauck** [parse-community/Parse-SDK-dotNET#304]
So I cannot get version 1.7 to work with a .NET standard library and VS 2017 15.9.3 so I followed the directions and built from source... added the using in my .NET Standard App.xaml.cs and then the Parse client initialize just before the main form is constructed.

I have a Xamarin.Forms app and when I try to run the UWP version I get the following error:
_Access to the path 'C:\Users\Stephen\source\repos\WatchMeWork\WatchMeWork.UWP\bin\x86\Debug\AppX\C' is denied.

   at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Parse.Internal.Utilities.StorageManager.GetWrapperForRelativePersistentStorageFilePath(String path)
   at Parse.ParseClient.Configuration.IdentifierBasedStorageConfiguration.get_RelativeStorageFilePath()
   at Parse.Internal.Utilities.StorageManager..cctor()_ 

I am not sure why Parse wants to write to the local path anyway but .... 

I haven't tried beyond UWP at this point ...

**Comment by TheFanatr** [comment]
Parse writes to a local path for installation caching purposes and some metadata stuff, but that is definitely not the kind of path it should be generating. Could you please post the initialization code you used (key and appId redacted)?

**Comment by TobiasPott** [comment]
I've faced this issue when coping with the caching file path when using Parse in Unity.
Inside the StoreManager classes `GetWrapperForRelativePersistentStorageFilePath(string path)`-method the `Path.VolumeSeparatorChar` character is used to crop down previously given path.

This leads to non-existing paths ending with '/C' (at least on windows platform and if the path does contain a 'C' at some point beyond the leading 'C:/').
Changing might resolve the issue you have. 
I did not test my code with UWP yet thus I cannot tell for sure why there is the need to select a portion of the string as the previously received path should be save to write the cache to. 

It doesn't look to me, that the `VolumeSeparatorChar` is a save one to use in this method in conjunction with the Substring and LastIndexOf calls. 
Any way I can think of, including the VolumeSeparatorChar would be odd, either trying to write to a possible non-existing directory or writing directly to the top-most level of the volume.
It might be more of a thing to use `DirectorySeparatorChar `or `AltDirectorySeparatorChar` in the LastIndexOf call

@stephenhauck Can you try replacing the VolumeSeparatorChar with DirectorySeparatorChar instead and see if it doesn't give the same error as above?

**Comment by kentrh** [comment]
I think maybe I'm facing the same or a similar issue.(https://stackoverflow.com/questions/55085681/parse-initialize-throws-ioexception-with-parse-net-sdk-on-net-core-2-2-hosted). @stephenhauck  Did you find a solution?

**Comment by TobiasPott** [comment]
@kentrh could you check if the fixes inside my feature branch might fix this issue on your side?https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/fix-currentinstallation-caching

I've had several issues within Unity regarding the path and caching location and also the trailing "\C" in the path (which comes from, as I assume, erroneous usage of the "VolumeSeparatorCharacter" when the storage file path is assembled).

Unfortunately I've got distracted on this and did not that much testing on it aside from what I need in my own application. If you could give it a try and tell me how it works for you, I'll try to pick up working on it and preparing a PR for the main repository.

**Comment by TobiasPott** [comment]
As this issue received no update for a while I close it.
The SDK should work fine on the UWP platform (including some configurations using mutators).
If this problem persist feel free to reopen this issue and provide additional information.
