### ISSUE TITLE
Android 8.0 and Unity 5.61f

### ISSUE THREAD

**Issue by suathh** [parse-community/Parse-SDK-dotNET#306]
This is not related to direclty to Parse SDK but it is one of important parts of problem.

So Parse SDK not working newer version of Unity we are currently using 5.6.1f1 and Parse SDK working fine. But in this version of Unity there is [bug ](https://forum.unity.com/threads/game-does-not-work-on-new-android-oreo.490142/) which is confirmed by Unity. Solution given by Unity Developers is updating version but if I update Unity then I can not work with Parse SDK.

Can't find a workaround yet.

**Comment by TobiasPott** [comment]
Hi suathh, 

Could you provide more information on this? I don't think we want to dig into the 3-paged-thread to find out which issue you might mean exactly.
If you can elaborate this issue a bit more, we might take it into account when a plugin for Unity support comes back on the list.

@TheFanatr did update the parse SDK to comply with .NET Standard. As far as I know this was first supported in Unity 2017.x and was not backported to the 5.x cycle.
I doubt that anything related to Unity versions without .NET Standard support will be handled within the current version of ParseSDK for .NET.

@TheFanatr stated his plans and ideas for the SDK [here](https://github.com/parse-community/Parse-SDK-dotNET/pull/298). Specific changes or adjustments for Unity are not on the list for now (for good reasons) and will require you to check for forks and make individual changes to your needs.
