### ISSUE TITLE
Unity 2018.2.20f1 switching runtime issue

### ISSUE THREAD

**Issue by vaspotapov** [parse-community/Parse-SDK-dotNET#307]
Hello, after switching runtime from 3.5 to 4.x Equivalent I've encountered this issue at the runtime

`MissingMethodException: bool UnityEngine.Application.get_isWebPlayer()
Parse.ParseClient.Initialize (Parse.ParseClient+Configuration configuration) (at <3a984a4e1cc34c4c8c294275204691d0>:0)
Parse.ParseClient.Initialize (System.String applicationId, System.String dotnetKey) (at <3a984a4e1cc34c4c8c294275204691d0>:0)
Parse.ParseInitializeBehaviour.Initialize () (at <3a984a4e1cc34c4c8c294275204691d0>:0)
Parse.ParseInitializeBehaviour.Awake () (at <3a984a4e1cc34c4c8c294275204691d0>:0)
UnityEngine.GameObject:SetActive()
ParseInitializer:InitParse() (at Assets/Scripts/Services/Parse/ParseInitializer.cs:109)
ParseInitializer:<InitWebConfig>m__1(Boolean) (at Assets/Scripts/Services/Parse/ParseInitializer.cs:74)
GeneralExtensions:Call(Action`1, Boolean) (at Assets/Scripts/Generic/Util/GeneralExtensions.cs:130)
<PingCoroutine>c__Iterator0:MoveNext() (at Assets/Scripts/Generic/Util/ConnectionUtils.cs:37)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

I know it's related to https://github.com/parse-community/Parse-SDK-dotNET/issues/294, but I was not able to find clear answer there

**Comment by vaspotapov** [comment]
So any help would be appreciated

**Comment by vaspotapov** [comment]
Wow! I didn't expect this much informativity, thanks a lot! Yeah, we are using latest 1.7.0 compiled from this repository. And yes, I've figure out how to workaround this problem. But there is another one appears 
`MissingMethodException: string UnityEngine.Application.get_bundleIdentifier()
Parse.ParseClient.Initialize (Parse.ParseClient+Configuration configuration) (at <2c6e68dbec7145fba432780312d66236>:0)
Parse.ParseClient.Initialize (System.String applicationId, System.String dotnetKey) (at <2c6e68dbec7145fba432780312d66236>:0)
Parse.ParseInitializeBehaviour.Initialize () (at <2c6e68dbec7145fba432780312d66236>:0)
Parse.ParseInitializeBehaviour.Awake () (at <2c6e68dbec7145fba432780312d66236>:0)
UnityEngine.GameObject:SetActive()`

And as you mentioned
>  The current state of this repository was made by Alex (@TheFanatr) and does not include specific support for Unity (which is planned for the future when a plugin system is reintroduced).

I assume that it is only possible way for use Parse service is to switch back to the .Net 3.5 version, right?

**Comment by vaspotapov** [comment]
Nevermind) resolved it)

**Comment by TobiasPott** [comment]
@vaspotapov although closed, could you list briefly what your solution was? Did you turn back .NET API compatibility level or also reverted to an older version of Unity in a way? (Just for the record, if someone else is coming across this thread).

**Comment by vaspotapov** [comment]
Offcourse. In PlatformHooks.Unity.cs we interested in two fields (bool isWebPlayer and string appDisplayVersion). So I just replaced declaration as this:
`isWebPlayer = Application.platform == RuntimePlatform.WebGLPlayer;
 appDisplayVersion = "com.companyName.gameName";`

**Comment by TobiasPott** [comment]
Great, thank you for this information. I believe this will help others when they come across this issue =)

**Comment by vaspotapov** [comment]
Yeah, you're right) Thanks for time and help!
