### ISSUE TITLE
[bug] when ParseQuery.Or a query, the condition checker is wrong.

### ISSUE THREAD

**Issue by wujun4code** [parse-community/Parse-SDK-dotNET#309]
https://github.com/parse-community/Parse-SDK-dotNET/blob/d0577f4d0979ddadce0c535146a572c3ca31fed0/Parse/Public/ParseQuery.cs#L188

```cs
if (!parameters.TryGetValue("where", out object where) || parameters.Count > 1)
                    throw new ArgumentException("None of the queries in an or query can have non-filtering clauses");
```
should be:

```cs
if (!parameters.TryGetValue("where", out object where) || parameters.Count < 1)
                    throw new ArgumentException("None of the queries in an or query can have non-filtering clauses");
```

**Comment by TobiasPott** [comment]
Hi @wujun4code 
thank you for reporting this issue, I'll have a look at this in the next days and in case I can reproduce it I'll integrate your suggested fix and prepare a pull request for it.
