### ISSUE TITLE
FCM Notifications Available for Xamarin.Android?

### ISSUE THREAD

**Issue by patkozlowski** [parse-community/Parse-SDK-dotNET#311]
Hello Experts,

I've been trying to implement FCM notifications for Xamarin.Android, but have ran into some roadblocks.  Looking in the documentation in the .NET Guide, for setting up push notifications for xamarin.android points to [this](http://docs.parseplatform.org/tutorials/android-push-notifications/), but on trying to run the application, I run into this error` Java.Lang.RuntimeException: Unable to instantiate service com.parse.fcm.ParseFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class`, Looking at the xamarin.android sdk, I don't see any references to FCM, only GCM.  Question is FCM supported in Xamarin.Android?  The documentation says it is, but I don't see any FCM references in the Parse Xamarin.Android SDK.  Looking for someone to point me in the right direction.

Thanks

**Comment by mmmmhh** [comment]
Hello, 
I have the same problem on Xamarin.Android after following the point to point documentation.

**Comment by SmatchyLaPaglia** [comment]
Same here, can't find any help.
