### ISSUE TITLE
Crashes on Wait() in Unity 2018.3.10

### ISSUE THREAD

**Issue by infosekr** [parse-community/Parse-SDK-dotNET#312]
AggregateException: Exception of type 'System.AggregateException' was thrown.
System.Threading.Tasks.Task.Wait ()
Parse.ParseUser.get_CurrentUser ()
Parse.ParseQuery`1[Parse.ParseObject].FindAsync (CancellationToken cancellationToken)
Parse.ParseQuery`1[Parse.ParseObject].FindAsync ()

https://github.com/parse-community/Parse-SDK-dotNET/blob/8d995277ea6b7119d2f67d6367c9b6de47277d4c/Parse/Public/ParseUser.cs#L322

**Comment by TobiasPott** [comment]
Hi @infosekr 

I'm sorry for the late response on your issue.
Could you please provide some more information in your issue? 
Did you initialized parse properly before doing any calls to it?

I'm using a modified version of this repo https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/recode-unity-support could you check if it makes any difference, as the main branch of the community repository does not contain unity specific code which causes the parse SDKto error inside Unity.

With the modified repo I've tested at least with 2018.3.6 and 2019.1.0 and do not get any exceptions from a call to ParseUser.CurrentUser (after proper initialization of Parse)

**Comment by infosekr** [comment]
Hi @TobiasPott,

Yes, am I initializing Parse before calling it. I have a working version of my code that initializes and calls queries on Parse using Unity 2018.1.3f1 without any problems. When I upgrade my project to 2018.3.10 then I notice this crash without changing any code in my project.

I'll give your modified version a try and let you know the results.

**Comment by TobiasPott** [comment]
@infosekr As no further feedback occured on this issue describing any problems, I assume this issue can be closed. Please add a comment if any problems persist (or open a new issue if they are unrelated to this one).
