### ISSUE TITLE
How to authorize with Facebook in Unity?

### ISSUE THREAD

**Issue by jthra037** [parse-community/Parse-SDK-dotNET#323]
Throughout the [.Net docs](https://docs.parseplatform.org/dotnet/guide/#facebook-users) and the [Unity docs](https://docs.parseplatform.org/unity/guide/#facebook-users) the class `ParseFacebookUtils` is used to interact in a way that integrates Parse and Facebook SDK seamlessly, eg.:
 `Task<ParseUser> logInTask = ParseFacebookUtils.LogInAsync(userId, accessToken, tokenExpiration);`
 With DLL's compiled from @TobiasPott 's [feature/recode-unity-support](https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/recode-unity-support) `ParseFacebookUtils` does not seem to exist, and I am not sure what the reccomended approach to third party authentication is (I am looking to implement Google and Facebook, in Unity 2018.4). 

Has this class been moved, if so to where? Is there another recommended mechanism for third party authentication now?

**Comment by TobiasPott** [comment]
Hi @jthra037 
Unfortunately the docs on the Parse SDK for .NET are not up to date (and have not been for quite some time, I'm actually not sure where those are maintained and how to change them). 
The ParseFacebookUtils class is no longer present as there is no other third party authentication integration with the Parse SDK itself. 
I cannot tell where it was moved to or if it would be possible to modify any old versions to the latest version of the Parse SDK but this would be a task open to take up by a helpful developer ;).

To answer your question: no there is no recommended mechanism on how to integrate third party auth with Parse which I know of for the current state of the master branch.

**Comment by jthra037** [comment]
Thank you for confirming my suspicions. I'll work something out for my application, and if I like how it turns out, maybe I'll move it into a feature?

**Comment by TobiasPott** [comment]
@jthra037 As mentioned in other issues related to third-party auth methods, these are no longer provided by the Parse SDK itself.
I close this issue due to the changes the SDK has undergone in the past year and leave it up to you to create a new issue if you believe it is important and/or can provide help or information about possible implementations.
We appreciate any help and suggestions to improve versatility of the SDK and fix as many problems as possible.
