### ISSUE TITLE
ParseInstallation.CurrentInstallation.SetDeviceTokenFromData(NSData deviceToken) may not be up to date for iOS 13.

### ISSUE THREAD

**Issue by SwingsetTheory** [parse-community/Parse-SDK-dotNET#338]
As per this website: https://nshipster.com/apns-device-tokens/ the format Apple uses for deviceTokens has changed, and I wonder if this requires an update to ParseInstallation.CurrentInstallation.SetDeviceTokenFromData(NSData deviceToken).

I am seeing irregularities with deviceTokens while registering for Push Notifications on Xamarin in Visual Studio Mac.

Sometimes devices seem to have no tokens at all. Sometimes the token shown on the Dashboard does not match those shown on the device.

**Comment by TobiasPott** [comment]
@SwingsetTheory I'm very confused where you came across the method you mentioned in the Parse SDK for .NET.
What version of the SDK are you using? 
I neither can find the method in the 1.7.0 nor the 2.0.0-develop version.

I have the feeling that this is either an even more outdated and unmaintained version than 1.7.0 or a different platform SDK (or some fork?)

**Comment by SwingsetTheory** [comment]
<img width="205" alt="Screen Shot 2020-07-21 at Jul 21  1 17 24 pm" src="https://user-images.githubusercontent.com/4856483/88085920-88bcfe00-cb54-11ea-89e3-e14a3910c6a3.png">

The warnings have to do with .NETFrameworks and shouldn't affect the available methods, should they?

**Comment by SwingsetTheory** [comment]
Found it, it's in the iOS SDK:

https://docs.parseplatform.org/ios/guide/#using-channels

But as this is a bug occurring in Xamarin and Visual Studio using Parse and C#, should it really be posted there? It's not actually a problem I'm having with iOS itself....

**Comment by SwingsetTheory** [comment]
I am unsure at this point that I have diagnosed the issue correctly. I deleted the problematic Installations and started over and they seem to be working correctly now.
