### ISSUE TITLE
Is there any clear docs on how to integrate ParseSDK on unity?

### ISSUE THREAD

**Issue by dlwlrma00** [parse-community/Parse-SDK-dotNET#340]

**Comment by TobiasPott** [comment]
No at the moment there is not if your question remains unspecific as is and what you mean by "clear docs".
Which version of Unity are you using and which version of the SDK are you trying to integrate?

Over the past months/years the SDK was not adopted to changes made by Unity and there are various solutions.
You may either check out my fork of this repository [https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/implement-target-platform-configurations](https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/implement-target-platform-configurations) and specifically the [Platforms.md](https://github.com/TobiasPott/Parse-SDK-dotNET/blob/feature/implement-target-platform-configurations/Platforms.md) which provides an example implementation to be used in Unity 2018 or newer.
Keep in mind that this version is based on the 1.7.0 version of this repository which is outdated and will be replaced by the version 2.0.0 in the future.

You may also use the 2.0.0-develop branch of this repository. There is a short guide to set up and initialize the SDK in Unity when you take a look on the master branch. This would be the initial starting points you could head towards to get started.

Feel free to ask your questions if you encounter problems.
