### ISSUE TITLE
[v2.0.0-develop-1][Xamarin] - FindAsync causes ArgumentNullException - Solution found

### ISSUE THREAD

**Issue by AlexeyStarkov** [parse-community/Parse-SDK-dotNET#345]
[v2.0.0-develop-1][Xamarin.Forms][Android]
 - confirmed on the master branch
 
Hello. I've found a bug trying to retrieve data from a database using Android (Xamarin.Forms). I've also managed to detect a reason.
1) It looks in this way:
![capture](https://user-images.githubusercontent.com/24221515/105690630-84efa700-5efc-11eb-99a8-37364f834b65.jpg)
2) An exception is caused in HostManifestData.Inferred property because Assembly.GetEntryAssembly() returns "null"
![capture1](https://user-images.githubusercontent.com/24221515/105691334-66d67680-5efd-11eb-90b8-64cfdac81f13.jpg)
I've also found a possible reason why it happens:
https://xamarin.github.io/bugzilla-archives/21/21097/bug.html

**Solution:**
Assembly.GetEntryAssembly() calls should be replaced to Assembly.GetExecutingAssembly() in HostManifestData.Inferred property getter of Parse/Infrastructure/HostManifestData.cs class.

**Comment by TobiasPott** [comment]
Sorry for the late response on this and I'm glad that you've found a solution already.
Your solution includes changing the source code, which might be fine in your case, but may not in others.

The intended way to solve this issue would be providing a custom-configured instance of `HostManifestData` as described in https://github.com/parse-community/Parse-SDK-dotNET#use-in-unity-client. This allow you to defined that SDK's part's behaviour to either use fixed values or use a different method to determine the inferred values.
This should be done when creating your ParseClient instance in code.

The need to do so, depends on the platform you are targeting with your project. iOS and Android are two of those and unfortunately I'm unaware of a list to determine on which platforms what methods `Assembly.Get[xxx]Assembly()` return proper values and which do not. Thus I would recommend to use the above described way to provide a custom configuration for your project and platform.

Kind regards
Tobias
