### ISSUE TITLE
Are there any plans for implementing localDataStore?

### ISSUE THREAD

**Issue by SmatchyLaPaglia** [parse-community/Parse-SDK-dotNET#346]
I am pleased to see some people who know how to do such things are helping Parse for .NET become more up-to-date. Are there any plans to add LocalDataStore?

**Comment by richardjrossiii** [comment]
As one of the people who was tangentially involved in the original version of LDS for the iOS and Android SDKs, I'd advise against it. LDS in its original form was fundamentally broken, and a nightmare to maintain. In particular; having to re-implement all of the query logic in the client led to lots of weird bugs; and unexpected discrepancies (even when documented) between the behavior of the client and server.

My recommendation would be if something like this were re-imagined; to simply be a 'dumb store' of objects; do not implement any querying or advanced operations on it.

**Comment by stephenhauck** [comment]
You are basically wanting to store JSON / complex objects in a local data store right ?

**Comment by GlueBalloon** [comment]
I don’t want to have to create a MySQL system to store local versions of the data on the server, and I *really* don’t want to have to figure out how to sync MySQL records with my Parse database. 

I’m surprised this seems like an unusual request, storing local versions of the data seems like it should be needed by virtually every project ever. 

I might be dumb about all this, but are most people just biting the bullet and creating and syncing some alternate database system for local storage?

**Comment by stephenhauck** [comment]
I don't use this because I have never seen the .NET version work well for Xamarin powered apps but I keep an eye on it HOPING!
If you want to simply store complex objects locally and such just use LiteDB .. it's super easy and stores jagged / complex objects and even supports upserting
