### ISSUE TITLE
Do Parse Push Notifications work when app is in background?

### ISSUE THREAD

**Issue by gusennan** [parse-community/Parse-SDK-dotNET#37]
We have been following the Parse for Xamarin Android tutorial as shown in this repository:

https://github.com/ParsePlatform/PushTutorial

And in the parse.com website tutorial.  Push notifications work just fine when the app is open, but as soon as the app is put into the background or is closed no push notifications are registered.  To see if this was a .NET SDK issue or a parse issue, we also went through the Parse Android (plain-java) Tutorial, which worked as expected.  There are some differences between the AndroidManifests in these two implementations, but in both cases we copied line-for-line what was in the Tutorials.  Is this a known issue or is something else needed in order to have pushes be registered with the device while the app is not open?  What I would like to happen is for this to occur, like it does for the vanilla-Android example:

![desired_outcome](https://cloud.githubusercontent.com/assets/624632/10485803/66efaece-728c-11e5-80b5-1d3558aa69ad.png)

Here is our Application class and copy of our AndroidManifest.xml

``` cs
using Android.App;
using Android.Runtime;
using Android.OS;
using Xamarin;
using System;
using RebuyApp.Green.Cart.Storage;
using System.Linq;
using ReactiveUI;
using Parse;

namespace RebuyApp.Android
{
#if DEBUG
[Application(Debuggable=true)]
#else
[Application(Debuggable=false)]
#endif

    public class RebuyApplication : Application 
    {
        AutoSuspendHelper suspendHelper;

        public RebuyApplication(IntPtr handle, JniHandleOwnership transfer) :
        base(handle, transfer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();

            suspendHelper = new AutoSuspendHelper(this);

            RxApp.SuspensionHost.CreateNewAppState = () => new Bootstrap();
            RxApp.SuspensionHost.SetupDefaultSuspendResume();

            ParseClient.Initialize("OUR-CLIENT-KEY",
                "OUR-.NET-KEY");
            ParsePush.ParsePushNotificationReceived += ParsePush.DefaultParsePushNotificationReceivedHandler;

        }
    }
}

```

``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.5.0" package="de.rebuy.android" android:versionCode="22">
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" />
    <application android:label="@string/app_name" android:theme="@style/RebuyTheme" android:debuggable="true" android:icon="@drawable/launcher_icon">
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="" />
        <service android:name="parse.ParsePushService" />
        <receiver android:name="parse.ParsePushBroadcastReceiver" 
        android:permission="com.google.android.c2dm.permission.SEND"
        android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="de.rebuy.android" />
            </intent-filter>
        </receiver>
    </application>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.LOCATION_HARDWARE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.BATTERY_STATS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_LOGS" />
    <uses-permission android:name="android.permission.BIND_NOTIFICATION_LISTENER_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:protectionLevel="signature"
    android:name="de.rebuy.android.permission.C2D_MESSAGE"/>
    <uses-permission android:name="de.rebuy.android.permission.C2D_MESSAGE" />
</manifest>
```

**Comment by richardjrossiii** [comment]
I'm not sure I have the context to answer this one. @hallucinogen or @grantland, do either of you know the status of .NET background push?

**Comment by armintelker** [comment]
have the same issue

**Comment by hallucinogen** [comment]
I should. Let me investigate.

**Comment by gusennan** [comment]
@hallucinogen Please let me know if there's any additional information I could provide.

**Comment by hallucinogen** [comment]
I've confirmed that this is a valid bug. Creating a PR to fix it.

**Comment by gusennan** [comment]
Hey @hallucinogen @armintelker 

We'd love to help or know when we might be able to expect a working implementation.  Alternatively, is there a workaround (like an older version of the sdk) that we might be able to use so that we could make some progress on our app.  If the bug, as reported, is a valid bug and doesn't allow background pushes, which I think it is, it's blocking us from including push notifications in our next version of our xamarin app.

**Comment by benjorsini** [comment]
Hi,

Same as @gusennan here. Is there a fallback plan, older sdk, beta sdk we can rely on ?
Thanks in advance for your answer.

**Comment by benjorsini** [comment]
The android service finally restarted on my device. I was able to receive a background push few minutes later even with the app killed from the task manager.
Device : OnePlusOne, SDK 1.6.1

Sorry for the noise :)

**Comment by gusennan** [comment]
@hallucinogen could you let us know where you think the issue is occurring?  Maybe we could help with the PR...

**Comment by hallucinogen** [comment]
Hi @gusennan, sorry it takes me a while to revisit this. The main issue is here: https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/Parse/ParsePushService.cs#L35. When the app is killed/in background it's possible that `ParsePush.parsePushNotificationReceived` is `null` or empty due to the memory of the app being cleared. `ParsePush.parsePushNotificationReceived` is usually being populated inside `Application`: https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/Parse.StarterProjects/CSharp/ParseXamarinPushSample/ParseXamarinPushSample/ParseApplication.cs#L26

The immediate fix is to fallback to call `DefaultParsePushNotificationReceivedHandler` (https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/Parse/ParsePush.Android.cs#L26) when `ParsePush.parsePushNotificationReceived` is `null` or empty. But that's defining a new behavior on its own and might not work as expected. It's definitely better than having nothing to be displayed when push notification is received, but there's no way for external developer to override the behavior in the future.

And that's why I'm still thinking about various way to fix it that would lead to better experience/flexibility in the future. Again, very sorry that it took so long to fix this.

**Comment by gusennan** [comment]
@hallucinogen I understand.  I've been reading through the Android (java) and this implementation over the past few days.  I don't think the problem is just the Application being killed, but also the ParsePushService being started and stopped (at any time) itself, too.  Additionally, consider when the phone is restarted--even if the service were maintained in memory during the life of the phone, the list of callbacks will not be there after a phone restart.

Delegates are immutable, aren't they?  Is there any way that a deep-copy of the handler could be passed into the ParsePushService at the beginning of the first application launch, serialized, saved and loaded for subsequent pushes?

**Comment by micheljung** [comment]
Is there any solution? It's blocking me as well; Notifications for foreground apps are rather not what you need ;-)

**Comment by mzekrallah** [comment]
hi guys .. any update to this ? i'm having same issue and it's a show stopper for us .. please help ..

**Comment by hallucinogen** [comment]
#153 will fix it. But I'll discuss with the team first to make sure we want to do this.
