### ISSUE TITLE
Add auto-release

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-dotNET#373]
Let's add auto-release to this repo. Even though there hasn't been much activity in the last couple of years, but it may help to motivate contributors to submit PR if they know we can merge and release fast.

**Comment by mtrezza** [comment]
@Werkezeugs could you please check out the latest release 3.0 that we've just published? I want to make sure it worked fine, before I merge your PR. Specifically whether the release 3.0.0 is set correctly in the Nuget package.

**Comment by Werkezeugs** [comment]
Hi @mtrezza yes, seems to work fine on my project now :)

In the meantime I found another bug related to this. The .Include() does not work as expected for anonym users. 
Will create a seperate PR for  this ;)

Thanks for the fast reply

**Comment by mtrezza** [comment]
Great, I already reviewed your PR and sent you some feedback - thanks for the fix!
