### ISSUE TITLE
Does ParseUser.CurrentUser block?

### ISSUE THREAD

**Issue by andymads** [parse-community/Parse-SDK-dotNET#50]
Does ParseUser.CurrentUser block?

Here's the code for the property.

`public static ParseUser CurrentUser
{
    get
    {
        Task<ParseUser> currentUserAsync = ParseUser.GetCurrentUserAsync ();
        currentUserAsync.Wait ();
        return currentUserAsync.Result;
    }
}`

Presumably the Wait call can cause a delay?

Is there a way to determine whether there's a current user logged in without calling ParseUser.CurrentUser? Or do I have to keep track of it myself?

**Comment by hallucinogen** [comment]
Hi @andymads, thanks for your report.

`ParseUser.CurrentUser` will block on some platforms (like Unity iOS), but it will work on some others (like WinRT). We're currently looking for a good fix for this.

Currently, there's no fix for this. The fastest and probably something that we want to do in the future is to publicize `ParseUser.GetCurrentUserAsync()`

What do you think @grantland, @nlutsenko, @richardjrossiii, @wangmengyan95

**Comment by andymads** [comment]
Will I'm targeting Unity iOS so this is interesting to me.

I'm using ParseUser.Current as a flag in some coroutines so it will be called once per frame - perhaps I need to rethink this.

**Comment by andymads** [comment]
Ok, on device I think it's generating 700 bytes of garbage every single frame.

**Comment by rihadavid** [comment]
@andymads see #32 for workaround

**Comment by montymxb** [comment]
Closing in favor of #32
