### ISSUE TITLE
Push notifications sent twice on android with dotNET SDK

### ISSUE THREAD

**Issue by SeriouslySam** [parse-community/Parse-SDK-dotNET#57]
The bug that has been fixed on Android platform on version 1.9.3 ("Fixed: Receiving duplicate pushes to the same application on the same device.") is apparently still present in the Unity SDK.

Whenever we send push notifications for android users, they receive them twice. This only happens on Android platform (not on iOS).

Example of the payload sent:
{ 
  "alert": "test5" 
}

**Comment by jbiscuit** [comment]
We are also encountering this issue. Seemingly related, if in testing I have reinstalled the app many times in succession, far more than two pushes can be received. For instance, I just received 51 occurrences of the same push.

**Comment by montymxb** [comment]
Closing as out of date. If this issue persists we'll reopen.
