### ISSUE TITLE
[Unity] Push is received when app is in foreground, but payload is empty

### ISSUE THREAD

**Issue by hahdouken** [parse-community/Parse-SDK-dotNET#78]
I'm using the following code in Unity to receive pushes while the app is in the foreground. This code is almost exactly what's in the [Parse Push Tutorial on Github](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FParsePlatform%2FPushTutorial%2Fblob%2Fmaster%2FUnity%2FAssets%2FPushBehaviour.cs&sa=D&sntz=1&usg=AFQjCNGwKDTvQ8SXoiEhyKOaQIh10GLgyg).

```
using UnityEngine;
using System.Collections.Generic;
using System.Collections;
using Parse;
using System;

public class PushBehaviour : MonoBehaviour {

// Use this for initialization
void Awake() {

    #if UNITY_IOS
    UnityEngine.iOS.NotificationServices.RegisterForNotifications(UnityEngine.iOS.NotificationType.Alert |
                                                                  UnityEngine.iOS.NotificationType.Badge |
                                                                  UnityEngine.iOS.NotificationType.Sound);
    #endif

    ParsePush.ParsePushNotificationReceived += (sender, args) => {

        #if UNITY_IOS

        //this is working!
        Debug.Log("Push Received!");

        //this only displays empty brackets: "{}"  ... where's the payload??
        Debug.Log(args.StringPayload);

        IDictionary<string, object> payload = args.Payload;

        //this is not working
        Debug.Log(payload["alert"]);

        foreach (var key in payload.Keys) {
            //this is not working
            Debug.Log("Payload: " + key + ": " + payload[key]);
        }
        #endif
    };
}
}
```

With this code, pushes are received but the payload is empty. I've confirmed that there is actually a payload - I can clearly see the "alert" text in the iOS notification when the app is in the background. I've tried sending pushes with `push.Data = new Dictionary<string, object> { {"alert", "test"} };` and also just with `push.Alert = "test";` and I've tried sending them from the app and from the Parse website. I also tried converting the Dictionary to IDictionary before sending, but nothing worked.

I'm using Unity 5.2.2, Parse Unity SDK 1.6.1, and Xcode 7.1

Is this a bug, or is there just a missing step in the Parse documentation?

Thanks!

**Comment by paulcking** [comment]
I'm seeing a similar issue with iOS.  In the UnityAppController.mm code, I can print the userInfo parameter in the application:didReceiveRemoteNotification: delegate method and it has "aps" and "parsePushId" keys.  But when this arrives in ParsePush.ParsePushNotificationReceived as the args parameter, the "aps" key is missing.

So... I can't get foreground push notifications on iOS.  Since other posts have indicated this is possible, wondering if a change has introduced this problem.

**Comment by richardjrossiii** [comment]
Whoops. Somehow this issue fell through the cracks (and wasn't pinged by our bot, even weirder).
I'm not 100% sure what's going on here, we may be running one of Unity's 'undocumented features'. 

I'll poke around the code and see what I can figure out.
