### ISSUE TITLE
Can't build in Release mode with Xamarin.Android

### ISSUE THREAD

**Issue by tkowalczyk** [parse-community/Parse-SDK-dotNET#88]
Hi, I am able to build project with `Parse SDK` component from [Xamarin Components](https://components.xamarin.com/view/parse) in `Debug` mode but when I am trying to do this in `Release` I am getting the following error:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android
.Common.targets: Error: 
Error executing task LinkAssemblies: error XA2006: Reference to metadata item
'Java.Lang.Object Android.OS.BaseBundle::Get(System.String)' (defined in 
'Parse.Android, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null') from 
'Parse.Android, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null' could 
not be resolved. (znajdzwc)`

**Comment by YARG** [comment]
Hi guys, we've just upgraded to 1.7.0 from 1.3.1 and we're now getting this on a release build.   Do you know how to resolve it?

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task LinkAssemblies: error XA2006: Reference to metadata item 'Java.Lang.Object Android.OS.BaseBundle::Get(System.String)' (defined in 'Parse.Android, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null') from 'Parse.Android, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. (waist)

Thanks for any help you can give.

**Comment by richardjrossiii** [comment]
You could attempt to turn off assembly linking, which we didn't fully support in the 1.7.0 release. It *should* work in 1.8.0+ though.

**Comment by YARG** [comment]
Hi Richard, thanks for this and sorry for the delay in getting back to you as I missed the notification.  What's the ETA with the release as I'd be happy to try out any beta versions if you're able to send me the Parse.Android.dll binary.

**Comment by YARG** [comment]
OK it looks like the problem was down to the fact that the Android client project was API 19, upgraded it to Lollipop and I was able to do a release build against 1.7.0.  Great stuff. Thanks

**Comment by montymxb** [comment]
Closing as out of date.
