### ISSUE TITLE
[Unity] RunDispatcher generating lots of garbage each frame

### ISSUE THREAD

**Issue by andymads** [parse-community/Parse-SDK-dotNET#92]
Noticed that ParseInitialiseBehaviour.RunDispatcher generates 410 bytes of garbage each frame when running on iOS device. This is a lot when compared to the rest of my project. Is it excessive or is this nothing to worry about?

**Comment by richardjrossiii** [comment]
This sounds like an IL2CPP bug (those are my *favorite* to debug)... You should not see any garbage generated by `RunDispatcher`, it's a super simple coroutine...

I'll look into it.

**Comment by andymads** [comment]
Well ParseUser.CurrentUser generates 0.7Kb on device. Is this expected?

**Comment by richardjrossiii** [comment]
Nope, definitely not expected. Although We've never run Parse compiled by IL2CPP through any memory profilers. It's possible (however unlikely) that this is our problem, but seeing as .NET is supposed to be all GC'd code, my best bet is that the blame does lie on IL2CPP.

**Comment by andymads** [comment]
Actually my build is not using IL2CPP. I've been using the Mono backend for development as it builds a lot quicker.

**Comment by richardjrossiii** [comment]
And so the plot thinkens...

Thanks for the additional info. This has me very curious where the blame truly lies, then.

**Comment by andymads** [comment]
Any news on this one?
